//! Table schema introspection and the link-time schema registry
//! (SPEC-001 §6, DM-040…DM-043).
//!
//! `#[fluxum::table]` (in `fluxum-macros`) generates, for every annotated
//! struct:
//!
//! 1. a `'static`, allocation-free [`TableSchema`] describing the table,
//! 2. an implementation of the [`Table`] trait, and
//! 3. an [`inventory`] registration ([`registry::TableDef`]) so the schema is
//!    collected **at link time** — no source-file scanning, no dynamic
//!    loading (DM-040, PRD OQ-1: `inventory` chosen, see the T1.1 task's
//!    `oq1-linktime-registry.md`).
//!
//! At startup, [`registry::Schema::assemble`] gathers every registered table
//! into a validated [`registry::Schema`]; `ServerBuilder::build()` (later
//! phase) calls it before opening any transport.

pub mod registry;

pub use registry::{Schema, TableDef, spatial_stream_advisory};

use crate::error::Result;
use crate::store::RowValue;

// Re-export so macro-generated code can register via
// `::fluxum_core::schema::inventory::submit!` without the user crate
// depending on `inventory` directly (verified in the OQ-1 spike).
pub use inventory;

/// One registered table. Generated by `#[fluxum::table]`; collected at link
/// time (DM-042).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TableSchema {
    /// Struct name; unique across the module.
    pub name: &'static str,
    /// Declaration order == FluxBIN column order (SPEC-006).
    pub columns: &'static [ColumnSchema],
    /// Column ordinals; `len == 1` unless composite (DM-002/DM-003).
    pub primary_key: &'static [u16],
    /// Ordinal of the `#[auto_inc]` column, if any (DM-004).
    pub auto_inc: Option<u16>,
    /// `Private` (default) | `Public` | `Global` (DM-005/DM-007).
    pub access: TableAccess,
    /// Partition-key column ordinal (DM-008, SPEC-007).
    pub partition_by: Option<u16>,
    /// Multi-column unique constraints (DM-006).
    pub unique: &'static [&'static [u16]],
    /// Secondary and spatial indexes (DM-030…DM-033).
    pub indexes: &'static [IndexSchema],
    /// Row-level visibility; `PublicAll` unless declared (DM-060/DM-061).
    pub visibility: VisibilityRule,
}

impl TableSchema {
    /// The column at `ordinal`, if in range.
    pub fn column(&self, ordinal: u16) -> Option<&'static ColumnSchema> {
        self.columns.get(usize::from(ordinal))
    }
}

/// One column of a [`TableSchema`] (DM-042).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ColumnSchema {
    /// Field name as declared on the struct.
    pub name: &'static str,
    /// Column type from the closed universe (§3).
    pub ty: FluxType,
}

/// Closed column type universe (SPEC-001 §3, DM-010…DM-012).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FluxType {
    /// `bool` — 1 byte.
    Bool,
    /// `i8`.
    I8,
    /// `i16`.
    I16,
    /// `i32`.
    I32,
    /// `i64`.
    I64,
    /// `u8`.
    U8,
    /// `u16`.
    U16,
    /// `u32`.
    U32,
    /// `u64`.
    U64,
    /// `f32`.
    F32,
    /// `f64`.
    F64,
    /// `String` — length-prefixed UTF-8.
    Str,
    /// `Vec<u8>` — length-prefixed raw bytes.
    Bytes,
    /// [`crate::types::Identity`] — 32 bytes.
    Identity,
    /// [`crate::types::ConnectionId`] — 16 bytes.
    ConnectionId,
    /// [`crate::types::EntityId`] — 8 bytes.
    EntityId,
    /// [`crate::types::Timestamp`] — 8 bytes.
    Timestamp,
    /// [`crate::types::Decimal`] — exact fixed-point (SPEC-017 CT-020):
    /// 16-byte `i128` unscaled + 1-byte scale, self-describing.
    Decimal,
    /// `Option<T>` — nullable column (DM-012).
    Option(&'static FluxType),
    /// `Vec<T>` — homogeneous list (DM-012).
    List(&'static FluxType),
}

impl FluxType {
    /// Whether this is a floating-point column type (`f32`/`f64`) — the only
    /// types valid under a spatial index (DM-032).
    pub const fn is_float(&self) -> bool {
        matches!(self, Self::F32 | Self::F64)
    }
}

/// A secondary index declaration (DM-030…DM-032).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IndexSchema {
    /// `#[index(btree(a, b, ...))]` — B-tree index, single or composite.
    BTree {
        /// Column ordinals in declared key order.
        columns: &'static [u16],
    },
    /// `#[spatial(quadtree(x, y))]` / `#[spatial(rtree(a, b, c, d))]`.
    Spatial {
        /// QuadTree or R-tree (SPEC-008).
        kind: SpatialKind,
        /// Coordinate column ordinals: 2 for quadtree, 4 for rtree.
        columns: &'static [u16],
    },
}

/// Spatial index family (DM-032, SPEC-008).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SpatialKind {
    /// 2D point geometry index.
    QuadTree,
    /// Bounding-box range-query index.
    RTree,
}

/// Table access class (DM-005/DM-007).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TableAccess {
    /// Server-internal only — never sent to clients (default).
    #[default]
    Private,
    /// Visible to client subscriptions.
    Public,
    /// Replicated read-only to all shards (SPEC-007).
    Global,
}

/// Row-level visibility rule (DM-060/DM-061, SPEC-005).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum VisibilityRule {
    /// All clients see all rows (default for `public` tables).
    #[default]
    PublicAll,
    /// Clients see only rows whose owner column equals their `Identity`.
    OwnerOnly {
        /// Ordinal of the `Identity`-typed owner column.
        owner: u16,
    },
    /// Clients see only rows belonging to their current shard.
    ShardLocal,
    /// Registered filter function `fn(row: &T, viewer: &Identity) -> bool`
    /// referenced by name (DM-061).
    Custom(&'static str),
}

/// Generated for each table struct by `#[fluxum::table]` (DM-043).
///
/// Consumed by the storage engine (SPEC-002) and the typed
/// [`crate::reducer::TxHandle`] accessors (SPEC-004, T3.2): the value
/// conversions bridge the typed struct and the store's dynamic
/// [`RowValue`] row representation. Wire-level FluxBIN encoding stays on
/// the storage side ([`crate::store`]) — this trait never sees bytes.
pub trait Table: Sized + 'static {
    /// Primary key type; a tuple for composite PKs, e.g. `(i32, i32)`.
    type Pk: Ord + Clone + Send;

    /// The link-time registered schema of this table.
    const SCHEMA: &'static TableSchema;

    /// This row's primary key (cloned out of the row).
    fn primary_key(&self) -> Self::Pk;

    /// This row's column values in declaration order (consumes the row) —
    /// the exact shape [`crate::store::Tx::insert`] takes.
    fn into_values(self) -> Vec<RowValue>;

    /// Rebuild a typed row from stored column values (declaration order).
    ///
    /// Errors on arity or column-type mismatch — unreachable for rows the
    /// store accepted for this same schema, but surfaced (not panicked) so
    /// the reducer path stays panic-free (RED-061).
    fn from_values(values: &[RowValue]) -> Result<Self>;

    /// The column values of `pk`, in `TableSchema::primary_key` declaration
    /// order — the exact shape [`crate::store::Tx::query_pk`] and
    /// [`crate::store::Tx::delete`] take.
    fn pk_values(pk: &Self::Pk) -> Vec<RowValue>;
}
