//! Table schema introspection and the link-time schema registry
//! (SPEC-001 §6, DM-040…DM-043).
//!
//! `#[fluxum::table]` (in `fluxum-macros`) generates, for every annotated
//! struct:
//!
//! 1. a `'static`, allocation-free [`TableSchema`] describing the table,
//! 2. an implementation of the [`Table`] trait, and
//! 3. an [`inventory`] registration ([`registry::TableDef`]) so the schema is
//!    collected **at link time** — no source-file scanning, no dynamic
//!    loading (DM-040, PRD OQ-1: `inventory` chosen, see the T1.1 task's
//!    `oq1-linktime-registry.md`).
//!
//! At startup, [`registry::Schema::assemble`] gathers every registered table
//! into a validated [`registry::Schema`]; `ServerBuilder::build()` (later
//! phase) calls it before opening any transport.

pub mod registry;

pub use registry::{Schema, TableDef, spatial_stream_advisory};

use crate::error::Result;
use crate::store::RowValue;

// Re-export so macro-generated code can register via
// `::fluxum_core::schema::inventory::submit!` without the user crate
// depending on `inventory` directly (verified in the OQ-1 spike).
pub use inventory;

/// One registered table. Generated by `#[fluxum::table]`; collected at link
/// time (DM-042).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TableSchema {
    /// Struct name; unique across the module.
    pub name: &'static str,
    /// Declaration order == FluxBIN column order (SPEC-006).
    pub columns: &'static [ColumnSchema],
    /// Column ordinals; `len == 1` unless composite (DM-002/DM-003).
    pub primary_key: &'static [u16],
    /// Ordinal of the `#[auto_inc]` column, if any (DM-004).
    pub auto_inc: Option<u16>,
    /// `Private` (default) | `Public` | `Global` (DM-005/DM-007).
    pub access: TableAccess,
    /// Partition-key column ordinal (DM-008, SPEC-007).
    pub partition_by: Option<u16>,
    /// Multi-column unique constraints (DM-006).
    pub unique: &'static [&'static [u16]],
    /// Secondary and spatial indexes (DM-030…DM-033).
    pub indexes: &'static [IndexSchema],
    /// Row-level visibility; `PublicAll` unless declared (DM-060/DM-061).
    pub visibility: VisibilityRule,
}

impl TableSchema {
    /// The column at `ordinal`, if in range.
    pub fn column(&self, ordinal: u16) -> Option<&'static ColumnSchema> {
        self.columns.get(usize::from(ordinal))
    }

    /// Whether this is an ephemeral (memory-only) table (SPEC-023 DMX-010).
    pub const fn is_ephemeral(&self) -> bool {
        self.access.is_ephemeral()
    }
}

/// One column of a [`TableSchema`] (DM-042).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ColumnSchema {
    /// Field name as declared on the struct.
    pub name: &'static str,
    /// Column type from the closed universe (§3).
    pub ty: FluxType,
}

/// Closed column type universe (SPEC-001 §3, DM-010…DM-012).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FluxType {
    /// `bool` — 1 byte.
    Bool,
    /// `i8`.
    I8,
    /// `i16`.
    I16,
    /// `i32`.
    I32,
    /// `i64`.
    I64,
    /// `u8`.
    U8,
    /// `u16`.
    U16,
    /// `u32`.
    U32,
    /// `u64`.
    U64,
    /// `f32`.
    F32,
    /// `f64`.
    F64,
    /// `String` — length-prefixed UTF-8.
    Str,
    /// `Vec<u8>` — length-prefixed raw bytes.
    Bytes,
    /// [`crate::types::Identity`] — 32 bytes.
    Identity,
    /// [`crate::types::ConnectionId`] — 16 bytes.
    ConnectionId,
    /// [`crate::types::EntityId`] — 8 bytes.
    EntityId,
    /// [`crate::types::Timestamp`] — 8 bytes.
    Timestamp,
    /// [`crate::types::Decimal`] — exact fixed-point (SPEC-017 CT-020):
    /// 16-byte `i128` unscaled + 1-byte scale, self-describing.
    Decimal,
    /// [`crate::types::BlobRef`] — 32-byte content-hash reference to a large
    /// object held out-of-row by the blob store (SPEC-023 DMX-040). The row
    /// never carries the payload bytes.
    Blob,
    /// `Option<T>` — nullable column (DM-012).
    Option(&'static FluxType),
    /// `Vec<T>` — homogeneous list (DM-012).
    List(&'static FluxType),
    /// A `#[derive(FluxType)]` tagged union (SPEC-023 DMX-030). FluxBIN:
    /// a `u8` variant tag (the ordinal) followed by the variant's payload.
    Enum(&'static EnumSchema),
    /// A `#[derive(FluxType)]` nested struct (SPEC-023 DMX-030). FluxBIN:
    /// its field values in declaration order, with no tag.
    Struct(&'static StructSchema),
}

impl FluxType {
    /// Whether this is a floating-point column type (`f32`/`f64`) — the only
    /// types valid under a spatial index (DM-032).
    pub const fn is_float(&self) -> bool {
        matches!(self, Self::F32 | Self::F64)
    }

    /// Whether this type can serve as a B-tree / primary key or spatial key.
    /// Rich types (enum/struct) and the variable/nested types are excluded —
    /// index/PK support is limited to the derivable memcomparable encoding
    /// (SPEC-023 DMX-031).
    pub const fn is_keyable(&self) -> bool {
        !matches!(
            self,
            Self::Enum(_) | Self::Struct(_) | Self::List(_) | Self::Option(_) | Self::Bytes
        )
    }
}

/// A derived tagged-union column type (SPEC-023 DMX-030). Variants are in
/// declaration order; the FluxBIN tag is the variant ordinal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EnumSchema {
    /// Enum type name.
    pub name: &'static str,
    /// Variants in declaration order (the FluxBIN tag equals the index).
    pub variants: &'static [VariantSchema],
}

/// One variant of an [`EnumSchema`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VariantSchema {
    /// Variant name.
    pub name: &'static str,
    /// Payload field types in declaration order; empty for a unit variant.
    pub payload: &'static [FluxType],
}

/// A derived nested-struct column type (SPEC-023 DMX-030).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StructSchema {
    /// Struct type name.
    pub name: &'static str,
    /// Fields in declaration order.
    pub fields: &'static [FieldSchema],
}

/// One field of a [`StructSchema`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FieldSchema {
    /// Field name.
    pub name: &'static str,
    /// Field column type.
    pub ty: FluxType,
}

/// A type usable as a rich column via `#[derive(FluxType)]` (SPEC-023
/// DMX-030): tagged-union enums and nested structs. Generated code bridges
/// the typed value and the dynamic [`RowValue`] the store holds — the trait
/// never sees bytes (FluxBIN stays on the storage side, like [`Table`]).
pub trait FluxTypeDef: Sized {
    /// The column-type descriptor — an [`FluxType::Enum`] or
    /// [`FluxType::Struct`].
    const FLUX_TYPE: FluxType;

    /// Convert into the dynamic row representation (consumes the value).
    fn to_row_value(self) -> RowValue;

    /// Rebuild from the dynamic row representation; errors on a shape or
    /// variant mismatch, never panics (RED-061).
    fn from_row_value(value: &RowValue) -> Result<Self>;
}

/// A secondary index declaration (DM-030…DM-032).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IndexSchema {
    /// `#[index(btree(a, b, ...))]` — B-tree index, single or composite.
    BTree {
        /// Column ordinals in declared key order.
        columns: &'static [u16],
    },
    /// `#[spatial(quadtree(x, y))]` / `#[spatial(rtree(a, b, c, d))]`.
    Spatial {
        /// QuadTree or R-tree (SPEC-008).
        kind: SpatialKind,
        /// Coordinate column ordinals: 2 for quadtree, 4 for rtree.
        columns: &'static [u16],
    },
    /// `#[fulltext(col, language, stop_words, stemming)]` — a positional
    /// inverted index over one `String`/`Vec<String>` column (SPEC-019
    /// FTS-001/010).
    FullText {
        /// Indexed text column ordinal.
        column: u16,
        /// Analyzer language (stop-word set + stemmer selection).
        language: FullTextLanguage,
        /// Drop language stop-words.
        stop_words: bool,
        /// Apply the language stemmer.
        stemming: bool,
    },
}

/// Full-text analyzer language (SPEC-019 FTS-010) — the schema-literal mirror
/// of [`crate::index::Language`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FullTextLanguage {
    /// Tokenize + case-fold only (language-agnostic).
    Simple,
    /// English stop-words + light English stemmer.
    English,
}

/// Spatial index family (DM-032, SPEC-008).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SpatialKind {
    /// 2D point geometry index.
    QuadTree,
    /// Bounding-box range-query index.
    RTree,
}

/// Table access class (DM-005/DM-007, SPEC-023 DMX-010).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TableAccess {
    /// Server-internal only — never sent to clients (default).
    #[default]
    Private,
    /// Visible to client subscriptions.
    Public,
    /// Replicated read-only to all shards (SPEC-007).
    Global,
    /// Memory-only and client-visible: rows fan out to subscribers like a
    /// `Public` table but bypass the commit log, checkpoints, and replication,
    /// and start empty after a restart (SPEC-023 DMX-010/012). Never durable,
    /// never replicated.
    Ephemeral,
}

impl TableAccess {
    /// Whether rows of this table are delivered to client subscriptions
    /// (`Public` or `Ephemeral`).
    pub const fn is_client_visible(self) -> bool {
        matches!(self, Self::Public | Self::Ephemeral)
    }

    /// Whether this table is ephemeral: memory-only, non-durable, and
    /// non-replicated (SPEC-023 DMX-010).
    pub const fn is_ephemeral(self) -> bool {
        matches!(self, Self::Ephemeral)
    }
}

/// Row-level visibility rule (DM-060/DM-061, SPEC-005).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum VisibilityRule {
    /// All clients see all rows (default for `public` tables).
    #[default]
    PublicAll,
    /// Clients see only rows whose owner column equals their `Identity`.
    OwnerOnly {
        /// Ordinal of the `Identity`-typed owner column.
        owner: u16,
    },
    /// Clients see only rows belonging to their current shard.
    ShardLocal,
    /// Registered filter function `fn(row: &T, viewer: &Identity) -> bool`
    /// referenced by name (DM-061).
    Custom(&'static str),
}

/// Cleanup metadata of one ephemeral table (SPEC-023 DMX-011), registered at
/// link time by `#[fluxum::table(ephemeral, ...)]` when the table declares an
/// `expire_after` and/or an `#[owner]` binding. Keyed by table name and kept
/// off [`TableSchema`] (side registry, like the SPEC-017 transforms) so the
/// additive metadata costs no change at its construction sites.
pub struct EphemeralDef {
    /// The `#[fluxum::table]` struct name.
    pub table: &'static str,
    /// Ordinal of the `#[owner]` `ConnectionId` column, if bound: the owner's
    /// rows are deleted (with delete diffs) when that connection drops.
    pub owner: Option<u16>,
    /// Row lifetime in microseconds since the last write, if declared: the
    /// sweeper drops older rows (at sweep-cadence granularity).
    pub expire_after_us: Option<i64>,
}

inventory::collect!(EphemeralDef);

/// Every registered ephemeral-cleanup def in this binary (linker order).
pub fn registered_ephemeral() -> impl Iterator<Item = &'static EphemeralDef> {
    inventory::iter::<EphemeralDef>()
}

/// The cleanup metadata of ephemeral `table`, if registered.
pub fn ephemeral_def(table: &str) -> Option<&'static EphemeralDef> {
    registered_ephemeral().find(|def| def.table == table)
}

/// Startup validation of every registered [`EphemeralDef`] against an
/// assembled schema (DMX-011 backstop; defs for tables outside `schema` are
/// skipped — the registry is process-global, schemas may be subsets).
pub(crate) fn validate_registered_ephemeral(schema: &Schema) -> Result<()> {
    use crate::error::FluxumError;
    for def in registered_ephemeral() {
        let Some(table) = schema.table(def.table) else {
            continue;
        };
        if !table.is_ephemeral() {
            return Err(FluxumError::Schema(format!(
                "table `{}`: ephemeral cleanup metadata on a non-ephemeral table (DMX-011)",
                def.table
            )));
        }
        if let Some(owner) = def.owner {
            let owner_ty = table.column(owner).map(|c| &c.ty);
            if !matches!(owner_ty, Some(FluxType::ConnectionId)) {
                return Err(FluxumError::Schema(format!(
                    "table `{}`: the #[owner] binding must be a `ConnectionId` column \
                     (DMX-011)",
                    def.table
                )));
            }
        }
        if let Some(us) = def.expire_after_us
            && us <= 0
        {
            return Err(FluxumError::Schema(format!(
                "table `{}`: expire_after must be positive (DMX-011)",
                def.table
            )));
        }
    }
    Ok(())
}

/// Generated for each table struct by `#[fluxum::table]` (DM-043).
///
/// Consumed by the storage engine (SPEC-002) and the typed
/// [`crate::reducer::TxHandle`] accessors (SPEC-004, T3.2): the value
/// conversions bridge the typed struct and the store's dynamic
/// [`RowValue`] row representation. Wire-level FluxBIN encoding stays on
/// the storage side ([`crate::store`]) — this trait never sees bytes.
pub trait Table: Sized + 'static {
    /// Primary key type; a tuple for composite PKs, e.g. `(i32, i32)`.
    type Pk: Ord + Clone + Send;

    /// The link-time registered schema of this table.
    const SCHEMA: &'static TableSchema;

    /// This row's primary key (cloned out of the row).
    fn primary_key(&self) -> Self::Pk;

    /// This row's column values in declaration order (consumes the row) —
    /// the exact shape [`crate::store::Tx::insert`] takes.
    fn into_values(self) -> Vec<RowValue>;

    /// Rebuild a typed row from stored column values (declaration order).
    ///
    /// Errors on arity or column-type mismatch — unreachable for rows the
    /// store accepted for this same schema, but surfaced (not panicked) so
    /// the reducer path stays panic-free (RED-061).
    fn from_values(values: &[RowValue]) -> Result<Self>;

    /// The column values of `pk`, in `TableSchema::primary_key` declaration
    /// order — the exact shape [`crate::store::Tx::query_pk`] and
    /// [`crate::store::Tx::delete`] take.
    fn pk_values(pk: &Self::Pk) -> Vec<RowValue>;
}
