//! `fluxum generate --lang csharp` (SPEC-011 SDK-060, FR-86): typed table row
//! records and reducer wrappers emitted from the frozen `/schema` document
//! (T6.1, T7.6).
//!
//! # What is emitted
//!
//! Two files in namespace `FluxumGen` — `Tables.cs` (a `record` row + a
//! decoder + the cache-hook `TableSchema` per table) and `Reducers.cs` (a
//! static `async Task` wrapper per client-callable reducer) — importing only
//! the runtime `Fluxum.Sdk` package.
//!
//! # Determinism (SPEC-011 acceptance 10/11)
//!
//! Pure function of the schema document: tables, reducers and columns are
//! emitted in document order and the file map is a `BTreeMap`, so regenerating
//! is byte-identical and offline generation matches URL generation.
//!
//! # Numeric types
//!
//! C# has fixed-width integers, so widths map exactly: `u64`/`i64` map to
//! `ulong`/`long` (no precision loss on a primary key). `Identity`,
//! `ConnectionId` surface as `string` (hex); `Timestamp` as `long` (µs).

use std::collections::BTreeMap;

use serde_json::Value;

fn header(schema_version: u64, document_version: u64) -> String {
    format!(
        "// Code generated by `fluxum generate --lang csharp`. DO NOT EDIT.\n\
         //\n\
         // schema_version:   {schema_version}   (the module's schema — SPEC-010 MIG-001)\n\
         // document_version: {document_version}   (the /schema shape — frozen at T6.1)\n\
         //\n\
         // Re-run the generator after a schema change; edits here are lost.\n\n"
    )
}

/// Map a schema column type (`FluxType` name) to its C# type.
fn column_type(flux: &str) -> &'static str {
    match flux {
        "Bool" => "bool",
        "I8" => "sbyte",
        "I16" => "short",
        "I32" => "int",
        "I64" | "Timestamp" => "long",
        "U8" => "byte",
        "U16" => "ushort",
        "U32" => "uint",
        "U64" | "EntityId" => "ulong",
        "F32" => "float",
        "F64" => "double",
        "Str" | "Identity" | "ConnectionId" => "string",
        "Bytes" => "byte[]",
        _ => "object",
    }
}

/// The concrete C# type `RowReader.Read` returns for a column type — what a
/// decoder casts from before assigning into the record field.
fn read_cs_type(flux: &str) -> &'static str {
    match flux {
        "Bool" => "bool",
        "I8" | "I16" | "I32" | "I64" | "Timestamp" => "long",
        "U8" | "U16" | "U32" | "U64" | "EntityId" => "ulong",
        "F32" | "F64" => "double",
        "Str" | "Identity" | "ConnectionId" => "string",
        "Bytes" => "byte[]",
        _ => "object",
    }
}

/// Map a reducer parameter's Rust source spelling to its C# type.
fn param_type(rust: &str) -> String {
    let rust = rust.replace(' ', "");
    let inner = |prefix: &str| -> Option<String> {
        rust.strip_prefix(prefix)
            .and_then(|r| r.strip_suffix('>'))
            .map(ToOwned::to_owned)
    };
    if let Some(inner) = inner("Option<") {
        return format!("{}?", param_type(&inner));
    }
    if let Some(inner) = inner("Vec<") {
        return if inner == "u8" {
            "byte[]".to_owned()
        } else {
            format!("{}[]", param_type(&inner))
        };
    }
    match rust.as_str() {
        "bool" => "bool",
        "i8" => "sbyte",
        "i16" => "short",
        "i32" => "int",
        "i64" | "i128" | "isize" => "long",
        "u8" => "byte",
        "u16" => "ushort",
        "u32" => "uint",
        "u64" | "u128" | "usize" => "ulong",
        "f32" => "float",
        "f64" => "double",
        "String" | "&str" | "str" | "Identity" | "ConnectionId" => "string",
        "Timestamp" => "long",
        _ => "object",
    }
    .to_owned()
}

fn is_decodable(flux: &str) -> bool {
    matches!(
        flux,
        "Bool"
            | "I8"
            | "I16"
            | "I32"
            | "I64"
            | "U8"
            | "U16"
            | "U32"
            | "U64"
            | "EntityId"
            | "F32"
            | "F64"
            | "Str"
            | "Bytes"
            | "Identity"
            | "ConnectionId"
            | "Timestamp"
    )
}

/// Upper-camel a `snake_case` name for a C# identifier. Names already in
/// PascalCase (table names) pass through unchanged.
fn pascal(name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in name.chars() {
        if ch == '_' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

pub fn generate(schema: &Value) -> Result<BTreeMap<String, String>, String> {
    let schema_version = schema
        .get("schema_version")
        .and_then(Value::as_u64)
        .ok_or("schema document has no `schema_version`")?;
    let document_version = schema
        .get("document_version")
        .and_then(Value::as_u64)
        .unwrap_or(1);
    let banner = header(schema_version, document_version);

    let tables = schema
        .get("tables")
        .and_then(Value::as_array)
        .ok_or("schema document has no `tables` array")?;
    let reducers = schema
        .get("reducers")
        .and_then(Value::as_array)
        .ok_or("schema document has no `reducers` array")?;

    let mut files = BTreeMap::new();
    files.insert("Tables.cs".to_owned(), tables_cs(&banner, tables)?);
    files.insert("Reducers.cs".to_owned(), reducers_cs(&banner, reducers)?);
    Ok(files)
}

fn tables_cs(banner: &str, tables: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str(
        "using System.Collections.Generic;\n\
         using Fluxum.Sdk;\n\n\
         namespace FluxumGen;\n\n\
         internal static class KeyProjection\n\
         {\n\
         \x20   public static string Project(byte[] data, (string Type, bool IsKey)[] plan)\n\
         \x20   {\n\
         \x20       var reader = new RowReader(data);\n\
         \x20       var parts = new List<string>();\n\
         \x20       foreach (var (type, isKey) in plan)\n\
         \x20       {\n\
         \x20           var value = reader.Read(type);\n\
         \x20           if (isKey) parts.Add(value?.ToString() ?? \"\");\n\
         \x20       }\n\
         \x20       return string.Join(\"|\", parts);\n\
         \x20   }\n\
         }\n\n",
    );

    for table in tables {
        let name = table
            .get("name")
            .and_then(Value::as_str)
            .ok_or("table has no name")?;
        let columns = table
            .get("columns")
            .and_then(Value::as_array)
            .ok_or_else(|| format!("table `{name}` has no columns"))?;
        let cs_name = pascal(name);
        let types: Vec<&str> = columns
            .iter()
            .map(|c| {
                c.get("type")
                    .and_then(Value::as_str)
                    .ok_or_else(|| format!("table `{name}` has an untyped column"))
            })
            .collect::<Result<_, _>>()?;
        for (i, ty) in types.iter().enumerate() {
            if !is_decodable(ty) {
                return Err(format!(
                    "table `{name}` column {i} has unmodelled type `{ty}`: the key \
                     projection cannot read it. Model the type or remove the column."
                ));
            }
        }

        // The record row.
        let fields: Vec<String> = columns
            .iter()
            .map(|c| {
                let col = c.get("name").and_then(Value::as_str).unwrap_or("");
                let ty = c.get("type").and_then(Value::as_str).unwrap_or("");
                format!("{} {}", column_type(ty), pascal(col))
            })
            .collect();
        out.push_str(&format!(
            "/// <summary>A row of the `{name}` table.</summary>\n"
        ));
        out.push_str(&format!(
            "public sealed record {cs_name}({});\n\n",
            fields.join(", ")
        ));

        // The decoder.
        out.push_str(&format!(
            "public static class {cs_name}Codec\n\
             {{\n\
             \x20   /// <summary>Decode one `{name}` row from its FluxBIN bytes.</summary>\n\
             \x20   public static {cs_name} Decode(byte[] row)\n\
             \x20   {{\n\
             \x20       var r = new RowReader(row);\n"
        ));
        let mut ctor_args = Vec::new();
        for column in columns {
            let ty = column.get("type").and_then(Value::as_str).unwrap_or("");
            let read_ty = read_cs_type(ty);
            let store_ty = column_type(ty);
            let var = format!("f{}", ctor_args.len());
            if read_ty == store_ty {
                out.push_str(&format!(
                    "\x20       var {var} = ({read_ty})r.Read({ty:?});\n"
                ));
            } else {
                out.push_str(&format!(
                    "\x20       var {var} = ({store_ty})({read_ty})r.Read({ty:?});\n"
                ));
            }
            ctor_args.push(var);
        }
        out.push_str(&format!(
            "\x20       return new {cs_name}({});\n\
             \x20   }}\n",
            ctor_args.join(", ")
        ));

        // The cache hooks.
        let pk_ordinals: Vec<usize> = table
            .get("primary_key")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_u64)
                    .map(|n| n as usize)
                    .collect()
            })
            .unwrap_or_default();
        let keys: Vec<usize> = if pk_ordinals.is_empty() {
            (0..types.len()).collect()
        } else {
            pk_ordinals
        };
        let pk_end = keys.iter().copied().max().map_or(0, |m| m + 1);
        let row_plan: Vec<String> = (0..pk_end)
            .map(|i| format!("({:?}, {})", types[i], keys.contains(&i)))
            .collect();
        let delete_plan: Vec<String> = keys
            .iter()
            .map(|i| format!("({:?}, true)", types[*i]))
            .collect();
        out.push_str(&format!(
            "\n\x20   /// <summary>The SDK cache hooks for `{name}` (SDK-040).</summary>\n\
             \x20   public static TableSchema TableSchema()\n\
             \x20   {{\n\
             \x20       var rowPlan = new (string, bool)[] {{ {row} }};\n\
             \x20       var deletePlan = new (string, bool)[] {{ {delete} }};\n\
             \x20       return new TableSchema(\n\
             \x20           {name:?},\n\
             \x20           b => KeyProjection.Project(b, rowPlan),\n\
             \x20           b => KeyProjection.Project(b, deletePlan));\n\
             \x20   }}\n\
             }}\n\n",
            row = row_plan.join(", "),
            delete = delete_plan.join(", "),
        ));
    }
    Ok(out)
}

fn reducers_cs(banner: &str, reducers: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str(
        "using System.Collections.Generic;\n\
         using System.Threading;\n\
         using System.Threading.Tasks;\n\
         using Fluxum.Sdk;\n\n\
         namespace FluxumGen;\n\n\
         public static class Reducers\n\
         {\n",
    );

    for reducer in reducers {
        let client_callable = reducer
            .get("client_callable")
            .and_then(Value::as_bool)
            .unwrap_or(true);
        if !client_callable {
            continue;
        }
        let name = reducer
            .get("name")
            .and_then(Value::as_str)
            .ok_or("reducer has no name")?;
        let cs_name = pascal(name);
        let params = reducer
            .get("params")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();

        let mut sig = String::from("Connection db");
        let mut args = Vec::new();
        for (i, param) in params.iter().enumerate() {
            let pname = param
                .get("name")
                .and_then(Value::as_str)
                .map(ToOwned::to_owned)
                .unwrap_or_else(|| format!("arg{i}"));
            let pty = param.get("type").and_then(Value::as_str).unwrap_or("");
            sig.push_str(&format!(", {} {pname}", param_type(pty)));
            args.push(pname);
        }
        // Fully-qualify the return `Task`: a table named `Task` would emit a
        // generated record of the same name and shadow System.Threading.Tasks.
        out.push_str(&format!(
            "\x20   /// <summary>Call the `{name}` reducer (RPC-021).</summary>\n\
             \x20   public static global::System.Threading.Tasks.Task {cs_name}({sig}, CancellationToken ct = default) =>\n\
             \x20       db.CallReducerAsync({name:?}, new object?[] {{ {args} }}, ct);\n\n",
            args = args.join(", "),
        ));
    }
    out.push_str("}\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;

    fn demo_schema() -> Value {
        serde_json::json!({
            "schema_version": 7,
            "document_version": 1,
            "tables": [{
                "name": "Task",
                "columns": [
                    { "name": "id", "type": "U64" },
                    { "name": "owner", "type": "Identity" },
                    { "name": "title", "type": "Str" },
                    { "name": "done", "type": "Bool" }
                ],
                "primary_key": [0]
            }],
            "reducers": [
                { "name": "add_task", "params": [{ "name": "title", "type": "String" }] },
                { "name": "sweep", "params": [], "client_callable": false }
            ]
        })
    }

    #[test]
    fn emits_typed_rows_decoders_and_reducer_wrappers() {
        let files = generate(&demo_schema()).unwrap();
        let tables = &files["Tables.cs"];
        assert!(tables.contains(
            "public sealed record Task(ulong Id, string Owner, string Title, bool Done);"
        ));
        assert!(tables.contains("public static Task Decode(byte[] row)"));
        assert!(tables.contains("public static TableSchema TableSchema()"));

        let reducers = &files["Reducers.cs"];
        assert!(reducers.contains(
            "public static global::System.Threading.Tasks.Task AddTask(Connection db, string title, CancellationToken ct = default)"
        ));
        assert!(!reducers.contains("Sweep("));
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(generate(&demo_schema()), generate(&demo_schema()));
    }

    #[test]
    fn an_unmodelled_column_type_is_refused() {
        let schema = serde_json::json!({
            "schema_version": 1,
            "tables": [{ "name": "T", "columns": [{ "name": "c", "type": "Wat" }], "primary_key": [0] }],
            "reducers": []
        });
        assert!(generate(&schema).unwrap_err().contains("unmodelled type"));
    }
}
