//! `fluxum generate --lang go` (SPEC-011 SDK-062, FR-85): typed table row
//! structs and reducer wrappers emitted from the frozen `/schema` document
//! (T6.1, T7.5).
//!
//! # What is emitted
//!
//! Two files in package `fluxumgen` — `tables.go` (a struct row + a decoder +
//! the cache-hook `TableSchema` per table) and `reducers.go` (a
//! context-aware typed wrapper per client-callable reducer) — importing only
//! the runtime `fluxum` package.
//!
//! # Determinism (SPEC-011 acceptance 10/11)
//!
//! Pure function of the schema document: tables, reducers and columns are
//! emitted in document order and the file map is a `BTreeMap`, so regenerating
//! is byte-identical and offline generation matches URL generation.
//!
//! # Numeric types
//!
//! Go has fixed-width integers, so widths map exactly: `u64`/`i64` map to
//! `uint64`/`int64` (no precision loss on a primary key). `Identity`,
//! `ConnectionId` surface as `string` (hex); `Timestamp` as `int64` (µs).

use std::collections::BTreeMap;

use serde_json::Value;

fn header(schema_version: u64, document_version: u64) -> String {
    format!(
        "// Code generated by `fluxum generate --lang go`. DO NOT EDIT.\n\
         //\n\
         // schema_version:   {schema_version}   (the module's schema — SPEC-010 MIG-001)\n\
         // document_version: {document_version}   (the /schema shape — frozen at T6.1)\n\
         //\n\
         // Re-run the generator after a schema change; edits here are lost.\n\n\
         package fluxumgen\n\n"
    )
}

/// Map a schema column type (`FluxType` name) to its Go type.
fn column_type(flux: &str) -> &'static str {
    match flux {
        "Bool" => "bool",
        "I8" => "int8",
        "I16" => "int16",
        "I32" => "int32",
        "I64" | "Timestamp" => "int64",
        "U8" => "uint8",
        "U16" => "uint16",
        "U32" => "uint32",
        "U64" | "EntityId" => "uint64",
        "F32" => "float32",
        "F64" => "float64",
        "Str" | "Identity" | "ConnectionId" => "string",
        "Bytes" => "[]byte",
        _ => "any",
    }
}

/// The concrete Go type the SDK's `RowReader.Read` returns for a column type —
/// what a decoder type-asserts before assigning into the struct field.
fn read_go_type(flux: &str) -> &'static str {
    match flux {
        "Bool" => "bool",
        "I8" | "I16" | "I32" | "I64" | "Timestamp" => "int64",
        "U8" | "U16" | "U32" | "U64" | "EntityId" => "uint64",
        "F32" | "F64" => "float64",
        "Str" | "Identity" | "ConnectionId" => "string",
        "Bytes" => "[]byte",
        _ => "any",
    }
}

/// Map a reducer parameter's Rust source spelling to its Go type.
fn param_type(rust: &str) -> String {
    let rust = rust.replace(' ', "");
    let inner = |prefix: &str| -> Option<String> {
        rust.strip_prefix(prefix)
            .and_then(|r| r.strip_suffix('>'))
            .map(ToOwned::to_owned)
    };
    if let Some(inner) = inner("Option<") {
        // Go has no Option; a nullable arg is a pointer.
        return format!("*{}", param_type(&inner));
    }
    if let Some(inner) = inner("Vec<") {
        return if inner == "u8" {
            "[]byte".to_owned()
        } else {
            format!("[]{}", param_type(&inner))
        };
    }
    match rust.as_str() {
        "bool" => "bool",
        "i8" => "int8",
        "i16" => "int16",
        "i32" => "int32",
        "i64" | "i128" | "isize" => "int64",
        "u8" => "uint8",
        "u16" => "uint16",
        "u32" => "uint32",
        "u64" | "u128" | "usize" => "uint64",
        "f32" => "float32",
        "f64" => "float64",
        "String" | "&str" | "str" | "Identity" | "ConnectionId" => "string",
        "Timestamp" => "int64",
        _ => "any",
    }
    .to_owned()
}

fn is_decodable(flux: &str) -> bool {
    matches!(
        flux,
        "Bool"
            | "I8"
            | "I16"
            | "I32"
            | "I64"
            | "U8"
            | "U16"
            | "U32"
            | "U64"
            | "EntityId"
            | "F32"
            | "F64"
            | "Str"
            | "Bytes"
            | "Identity"
            | "ConnectionId"
            | "Timestamp"
    )
}

/// Upper-camel a `snake_case` name for an exported Go identifier.
fn exported(name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in name.chars() {
        if ch == '_' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

pub fn generate(schema: &Value) -> Result<BTreeMap<String, String>, String> {
    let schema_version = schema
        .get("schema_version")
        .and_then(Value::as_u64)
        .ok_or("schema document has no `schema_version`")?;
    let document_version = schema
        .get("document_version")
        .and_then(Value::as_u64)
        .unwrap_or(1);
    let banner = header(schema_version, document_version);

    let tables = schema
        .get("tables")
        .and_then(Value::as_array)
        .ok_or("schema document has no `tables` array")?;
    let reducers = schema
        .get("reducers")
        .and_then(Value::as_array)
        .ok_or("schema document has no `reducers` array")?;

    let mut files = BTreeMap::new();
    files.insert("tables.go".to_owned(), tables_go(&banner, tables)?);
    files.insert("reducers.go".to_owned(), reducers_go(&banner, reducers)?);
    Ok(files)
}

fn tables_go(banner: &str, tables: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str(
        "import (\n\
         \t\"fmt\"\n\
         \t\"strings\"\n\n\
         \tfluxum \"github.com/hivellm/fluxum/fluxum\"\n\
         )\n\n",
    );
    // A shared key-projection helper (emitted once).
    out.push_str(
        "// projectKey reads `plan` in wire order, joining the key parts.\n\
         func projectKey(data []byte, plan [][2]any) string {\n\
         \treader := fluxum.NewRowReader(data)\n\
         \tparts := make([]string, 0, len(plan))\n\
         \tfor _, p := range plan {\n\
         \t\tv, _ := reader.Read(p[0].(string))\n\
         \t\tif p[1].(bool) {\n\
         \t\t\tparts = append(parts, fmt.Sprintf(\"%v\", v))\n\
         \t\t}\n\
         \t}\n\
         \treturn strings.Join(parts, \"|\")\n\
         }\n\n",
    );

    for table in tables {
        let name = table
            .get("name")
            .and_then(Value::as_str)
            .ok_or("table has no name")?;
        let columns = table
            .get("columns")
            .and_then(Value::as_array)
            .ok_or_else(|| format!("table `{name}` has no columns"))?;
        let go_name = exported(name);
        let types: Vec<&str> = columns
            .iter()
            .map(|c| {
                c.get("type")
                    .and_then(Value::as_str)
                    .ok_or_else(|| format!("table `{name}` has an untyped column"))
            })
            .collect::<Result<_, _>>()?;
        for (i, ty) in types.iter().enumerate() {
            if !is_decodable(ty) {
                return Err(format!(
                    "table `{name}` column {i} has unmodelled type `{ty}`: the key \
                     projection cannot read it. Model the type or remove the column."
                ));
            }
        }

        // The row struct.
        out.push_str(&format!("// {go_name} is a row of the `{name}` table.\n"));
        out.push_str(&format!("type {go_name} struct {{\n"));
        for column in columns {
            let col = column
                .get("name")
                .and_then(Value::as_str)
                .ok_or("column has no name")?;
            let ty = column.get("type").and_then(Value::as_str).unwrap_or("");
            out.push_str(&format!("\t{} {}\n", exported(col), column_type(ty)));
        }
        out.push_str("}\n\n");

        // The decoder.
        out.push_str(&format!(
            "// Decode{go_name} decodes one `{name}` row from its FluxBIN bytes.\n\
             func Decode{go_name}(row []byte) ({go_name}, error) {{\n\
             \tr := fluxum.NewRowReader(row)\n\
             \tvar out {go_name}\n"
        ));
        for column in columns {
            let col = column.get("name").and_then(Value::as_str).unwrap_or("");
            let ty = column.get("type").and_then(Value::as_str).unwrap_or("");
            let go_field = exported(col);
            let read_ty = read_go_type(ty);
            let store_ty = column_type(ty);
            out.push_str(&format!(
                "\tif v, err := r.Read({:?}); err != nil {{\n\
                 \t\treturn out, err\n\
                 \t}} else {{\n",
                ty
            ));
            if read_ty == store_ty {
                out.push_str(&format!("\t\tout.{go_field} = v.({read_ty})\n"));
            } else {
                // e.g. an I32 column: read int64, narrow into int32.
                out.push_str(&format!("\t\tout.{go_field} = {store_ty}(v.({read_ty}))\n"));
            }
            out.push_str("\t}\n");
        }
        out.push_str("\treturn out, nil\n}\n\n");

        // The cache hooks.
        let pk_ordinals: Vec<usize> = table
            .get("primary_key")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_u64)
                    .map(|n| n as usize)
                    .collect()
            })
            .unwrap_or_default();
        let keys: Vec<usize> = if pk_ordinals.is_empty() {
            (0..types.len()).collect()
        } else {
            pk_ordinals
        };
        let pk_end = keys.iter().copied().max().map_or(0, |m| m + 1);
        let row_plan: Vec<String> = (0..pk_end)
            .map(|i| format!("{{{:?}, {}}}", types[i], keys.contains(&i)))
            .collect();
        let delete_plan: Vec<String> = keys
            .iter()
            .map(|i| format!("{{{:?}, true}}", types[*i]))
            .collect();
        out.push_str(&format!(
            "// TableSchema{go_name} is the SDK cache hooks for `{name}` (SDK-040).\n\
             func TableSchema{go_name}() fluxum.TableSchema {{\n\
             \trowPlan := [][2]any{{{row}}}\n\
             \tdeletePlan := [][2]any{{{delete}}}\n\
             \treturn fluxum.TableSchema{{\n\
             \t\tName:       {name:?},\n\
             \t\tPkOfRow:    func(b []byte) string {{ return projectKey(b, rowPlan) }},\n\
             \t\tPkOfDelete: func(b []byte) string {{ return projectKey(b, deletePlan) }},\n\
             \t}}\n\
             }}\n\n",
            row = row_plan.join(", "),
            delete = delete_plan.join(", "),
        ));
    }
    Ok(out)
}

fn reducers_go(banner: &str, reducers: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str(
        "import (\n\
         \t\"context\"\n\n\
         \tfluxum \"github.com/hivellm/fluxum/fluxum\"\n\
         )\n\n",
    );

    for reducer in reducers {
        let client_callable = reducer
            .get("client_callable")
            .and_then(Value::as_bool)
            .unwrap_or(true);
        if !client_callable {
            continue;
        }
        let name = reducer
            .get("name")
            .and_then(Value::as_str)
            .ok_or("reducer has no name")?;
        let go_name = exported(name);
        let params = reducer
            .get("params")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();

        let mut sig = String::from("db *fluxum.Connection");
        let mut arg_names = Vec::new();
        for (i, param) in params.iter().enumerate() {
            let pname = param
                .get("name")
                .and_then(Value::as_str)
                .map(ToOwned::to_owned)
                .unwrap_or_else(|| format!("arg{i}"));
            let pty = param.get("type").and_then(Value::as_str).unwrap_or("");
            sig.push_str(&format!(", {pname} {}", param_type(pty)));
            arg_names.push(pname);
        }
        out.push_str(&format!(
            "// {go_name} calls the `{name}` reducer (RPC-021).\n\
             func {go_name}(ctx context.Context, {sig}) error {{\n\
             \treturn db.CallReducer(ctx, {name:?}, []any{{{args}}})\n\
             }}\n\n",
            args = arg_names.join(", "),
        ));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;

    fn demo_schema() -> Value {
        serde_json::json!({
            "schema_version": 7,
            "document_version": 1,
            "tables": [{
                "name": "Task",
                "columns": [
                    { "name": "id", "type": "U64" },
                    { "name": "owner", "type": "Identity" },
                    { "name": "title", "type": "Str" },
                    { "name": "done", "type": "Bool" }
                ],
                "primary_key": [0]
            }],
            "reducers": [
                { "name": "add_task", "params": [{ "name": "title", "type": "String" }] },
                { "name": "sweep", "params": [], "client_callable": false }
            ]
        })
    }

    #[test]
    fn emits_typed_rows_decoders_and_reducer_wrappers() {
        let files = generate(&demo_schema()).unwrap();
        let tables = &files["tables.go"];
        assert!(tables.contains("type Task struct {"));
        assert!(tables.contains("Id uint64"));
        assert!(tables.contains("Owner string"));
        assert!(tables.contains("Done bool"));
        assert!(tables.contains("func DecodeTask(row []byte) (Task, error)"));
        assert!(tables.contains("func TableSchemaTask() fluxum.TableSchema"));

        let reducers = &files["reducers.go"];
        assert!(reducers.contains(
            "func AddTask(ctx context.Context, db *fluxum.Connection, title string) error"
        ));
        assert!(!reducers.contains("func Sweep("));
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(generate(&demo_schema()), generate(&demo_schema()));
    }

    #[test]
    fn an_unmodelled_column_type_is_refused() {
        let schema = serde_json::json!({
            "schema_version": 1,
            "tables": [{ "name": "T", "columns": [{ "name": "c", "type": "Wat" }], "primary_key": [0] }],
            "reducers": []
        });
        assert!(generate(&schema).unwrap_err().contains("unmodelled type"));
    }
}
