//! `fluxum generate --lang python` (SPEC-011 SDK-061, FR-83): typed table
//! row classes and reducer wrappers emitted from the frozen `/schema`
//! document (T6.1, T7.4).
//!
//! # What is emitted
//!
//! Four files — `tables.py` (a `@dataclass` row + a decoder + the cache-hook
//! `TableSchema` per table), `reducers.py` (a typed async wrapper per
//! client-callable reducer), `__init__.py` (re-exports), and `py.typed` (the
//! PEP 561 marker) — importing only the runtime `fluxum` package. The
//! generated code is fully type-hinted, so `mypy`/`pyright` check it and an
//! editor completes it.
//!
//! # Determinism (SPEC-011 acceptance 10/11)
//!
//! Pure function of the schema document: tables, reducers and columns are
//! emitted in document order (the server already sorts them) and the file map
//! is a `BTreeMap`, so regenerating is byte-identical and offline generation
//! from a saved `schema.json` matches URL generation.
//!
//! # Numeric types
//!
//! Python `int` is unbounded, so every integer width — including `u64`/`i64`
//! primary keys — maps to `int` with no precision loss. `Identity`,
//! `ConnectionId` surface as `str` (hex); `Timestamp` as `int` (µs).

use std::collections::BTreeMap;

use serde_json::Value;

/// The generated-file banner (SPEC-011 acceptance 11).
fn header(schema_version: u64, document_version: u64) -> String {
    format!(
        "# Code generated by `fluxum generate --lang python`. DO NOT EDIT.\n\
         #\n\
         # schema_version:   {schema_version}   (the module's schema — SPEC-010 MIG-001)\n\
         # document_version: {document_version}   (the /schema shape — frozen at T6.1)\n\
         #\n\
         # Re-run the generator after a schema change; edits here are lost.\n\n"
    )
}

/// Map a schema column type (`FluxType` name) to its Python type hint.
fn column_type(flux: &str) -> &'static str {
    match flux {
        "Bool" => "bool",
        "I8" | "I16" | "I32" | "I64" | "U8" | "U16" | "U32" | "U64" | "EntityId" | "Timestamp" => {
            "int"
        }
        "F32" | "F64" => "float",
        "Str" | "Identity" | "ConnectionId" => "str",
        "Bytes" => "bytes",
        // An unmodelled type surfaces as `object` rather than a guess.
        _ => "object",
    }
}

/// Map a reducer parameter's Rust source spelling to its Python type hint.
fn param_type(rust: &str) -> String {
    let rust = rust.replace(' ', "");
    let inner = |prefix: &str| -> Option<String> {
        rust.strip_prefix(prefix)
            .and_then(|r| r.strip_suffix('>'))
            .map(ToOwned::to_owned)
    };
    if let Some(inner) = inner("Option<") {
        return format!("Optional[{}]", param_type(&inner));
    }
    if let Some(inner) = inner("Vec<") {
        return if inner == "u8" {
            "bytes".to_owned()
        } else {
            format!("list[{}]", param_type(&inner))
        };
    }
    match rust.as_str() {
        "bool" => "bool",
        "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "i128" | "u128" | "usize"
        | "isize" => "int",
        "f32" | "f64" => "float",
        "String" | "&str" | "str" => "str",
        "Identity" | "ConnectionId" => "str",
        "Timestamp" => "int",
        _ => "object",
    }
    .to_owned()
}

/// Whether the SDK's `RowReader` models this column type (an unmodelled type
/// desyncs every column after it, so it is refused at generation).
fn is_decodable(flux: &str) -> bool {
    matches!(
        flux,
        "Bool"
            | "I8"
            | "I16"
            | "I32"
            | "I64"
            | "U8"
            | "U16"
            | "U32"
            | "U64"
            | "EntityId"
            | "F32"
            | "F64"
            | "Str"
            | "Bytes"
            | "Identity"
            | "ConnectionId"
            | "Timestamp"
    )
}

/// Generate the Python binding files from a `/schema` document.
pub fn generate(schema: &Value) -> Result<BTreeMap<String, String>, String> {
    let schema_version = schema
        .get("schema_version")
        .and_then(Value::as_u64)
        .ok_or("schema document has no `schema_version`")?;
    let document_version = schema
        .get("document_version")
        .and_then(Value::as_u64)
        .unwrap_or(1);
    let banner = header(schema_version, document_version);

    let tables = schema
        .get("tables")
        .and_then(Value::as_array)
        .ok_or("schema document has no `tables` array")?;
    let reducers = schema
        .get("reducers")
        .and_then(Value::as_array)
        .ok_or("schema document has no `reducers` array")?;

    let mut files = BTreeMap::new();
    files.insert("tables.py".to_owned(), tables_py(&banner, tables)?);
    files.insert("reducers.py".to_owned(), reducers_py(&banner, reducers)?);
    files.insert(
        "__init__.py".to_owned(),
        init_py(&banner, tables, reducers)?,
    );
    files.insert("py.typed".to_owned(), String::new());
    Ok(files)
}

fn column_name<'a>(column: &'a Value) -> Result<&'a str, String> {
    column
        .get("name")
        .and_then(Value::as_str)
        .ok_or_else(|| "column has no name".to_owned())
}

fn column_flux<'a>(column: &'a Value, table: &str) -> Result<&'a str, String> {
    column
        .get("type")
        .and_then(Value::as_str)
        .ok_or_else(|| format!("table `{table}` has an untyped column"))
}

fn table_name<'a>(table: &'a Value) -> Result<&'a str, String> {
    table
        .get("name")
        .and_then(Value::as_str)
        .ok_or_else(|| "table has no name".to_owned())
}

fn table_columns<'a>(table: &'a Value, name: &str) -> Result<&'a Vec<Value>, String> {
    table
        .get("columns")
        .and_then(Value::as_array)
        .ok_or_else(|| format!("table `{name}` has no columns"))
}

fn pk_ordinals(table: &Value) -> Vec<usize> {
    table
        .get("primary_key")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(Value::as_u64)
                .map(|n| n as usize)
                .collect()
        })
        .unwrap_or_default()
}

fn tables_py(banner: &str, tables: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str(
        "\"\"\"Typed rows, decoders, and cache hooks for each table.\"\"\"\n\n\
         from __future__ import annotations\n\n\
         from dataclasses import dataclass\n\n\
         from fluxum import RowReader, TableSchema, decode_row\n\n",
    );

    for table in tables {
        let name = table_name(table)?;
        let columns = table_columns(table, name)?;
        let types: Vec<&str> = columns
            .iter()
            .map(|c| column_flux(c, name))
            .collect::<Result<_, _>>()?;
        for (i, ty) in types.iter().enumerate() {
            if !is_decodable(ty) {
                return Err(format!(
                    "table `{name}` column {i} has unmodelled type `{ty}`: the key \
                     projection cannot read it. Model the type or remove the column."
                ));
            }
        }

        // The `@dataclass` row.
        out.push_str(&format!("@dataclass(frozen=True)\nclass {name}:\n"));
        out.push_str(&format!("    \"\"\"A row of the `{name}` table.\"\"\"\n\n"));
        for column in columns {
            let col = column_name(column)?;
            let ty = column_flux(column, name)?;
            out.push_str(&format!("    {col}: {}\n", column_type(ty)));
        }
        out.push('\n');

        // The column descriptor list + a typed decoder.
        let descriptors: Vec<String> = columns
            .iter()
            .map(|c| {
                Ok::<String, String>(format!(
                    "(\"{}\", \"{}\")",
                    column_name(c)?,
                    column_flux(c, name)?
                ))
            })
            .collect::<Result<_, _>>()?;
        out.push_str(&format!(
            "_{name}_COLUMNS = [{}]\n\n\n",
            descriptors.join(", ")
        ));
        out.push_str(&format!(
            "def decode_{name}(row: bytes) -> {name}:\n\
             \x20   \"\"\"Decode one `{name}` row from its FluxBIN bytes.\"\"\"\n\
             \x20   values = decode_row(row, _{name}_COLUMNS)\n\
             \x20   return {name}(**values)\n\n\n"
        ));

        // The cache hooks: pk projection over the full-row and delete layouts.
        let keys: Vec<usize> = {
            let pk = pk_ordinals(table);
            if pk.is_empty() {
                (0..types.len()).collect()
            } else {
                pk
            }
        };
        let pk_end = keys.iter().copied().max().map_or(0, |m| m + 1);
        let row_plan: Vec<String> = (0..pk_end)
            .map(|i| format!("(\"{}\", {})", types[i], py_bool(keys.contains(&i))))
            .collect();
        let delete_plan: Vec<String> = keys
            .iter()
            .map(|i| format!("(\"{}\", True)", types[*i]))
            .collect();
        out.push_str(&format!(
            "def table_schema_{name}() -> TableSchema:\n\
             \x20   \"\"\"The SDK cache hooks for `{name}` (SDK-040): stable primary-key\n\
             \x20   projections over the full-row and delete-entry wire layouts.\"\"\"\n\
             \x20   row_plan = [{row}]\n\
             \x20   delete_plan = [{delete}]\n\
             \x20   return TableSchema(\n\
             \x20       \"{name}\",\n\
             \x20       lambda b: _project_key(b, row_plan),\n\
             \x20       lambda b: _project_key(b, delete_plan),\n\
             \x20   )\n\n\n",
            row = row_plan.join(", "),
            delete = delete_plan.join(", "),
        ));
    }

    out.push_str(
        "def _project_key(data: bytes, plan: list) -> str:\n\
         \x20   \"\"\"Read `plan` in wire order, joining the values marked as key parts.\"\"\"\n\
         \x20   reader = RowReader(data)\n\
         \x20   parts = []\n\
         \x20   for flux_type, is_key in plan:\n\
         \x20       value = reader.read(flux_type)\n\
         \x20       if is_key:\n\
         \x20           parts.append(str(value))\n\
         \x20   return \"|\".join(parts)\n",
    );
    Ok(out)
}

fn py_bool(b: bool) -> &'static str {
    if b { "True" } else { "False" }
}

fn reducers_py(banner: &str, reducers: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str(
        "\"\"\"Typed async wrappers for each client-callable reducer.\"\"\"\n\n\
         from __future__ import annotations\n\n\
         from typing import Optional\n\n\
         from fluxum import Connection\n\n",
    );

    for reducer in reducers {
        let client_callable = reducer
            .get("client_callable")
            .and_then(Value::as_bool)
            .unwrap_or(true);
        if !client_callable {
            continue; // schedule-only reducers are not callable from a client
        }
        let name = reducer
            .get("name")
            .and_then(Value::as_str)
            .ok_or("reducer has no name")?;
        let params = reducer
            .get("params")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();

        let mut sig = String::from("db: Connection");
        let mut arg_names = Vec::new();
        for (i, param) in params.iter().enumerate() {
            let pname = param
                .get("name")
                .and_then(Value::as_str)
                .map(ToOwned::to_owned)
                .unwrap_or_else(|| format!("arg{i}"));
            let pty = param.get("type").and_then(Value::as_str).unwrap_or("");
            sig.push_str(&format!(", {pname}: {}", param_type(pty)));
            arg_names.push(pname);
        }
        let args_list = arg_names.join(", ");
        out.push_str(&format!(
            "async def {name}({sig}) -> None:\n\
             \x20   \"\"\"Call the `{name}` reducer (RPC-021).\"\"\"\n\
             \x20   await db.call_reducer(\"{name}\", [{args_list}])\n\n\n"
        ));
    }
    Ok(out)
}

fn init_py(banner: &str, tables: &[Value], reducers: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str("\"\"\"Generated Fluxum bindings.\"\"\"\n\n");

    let mut exports: Vec<String> = Vec::new();
    let mut table_syms: Vec<String> = Vec::new();
    for table in tables {
        let name = table_name(table)?;
        table_syms.push(name.to_owned());
        table_syms.push(format!("decode_{name}"));
        table_syms.push(format!("table_schema_{name}"));
    }
    if !table_syms.is_empty() {
        out.push_str(&format!("from .tables import {}\n", table_syms.join(", ")));
        exports.extend(table_syms);
    }

    let reducer_syms: Vec<String> = reducers
        .iter()
        .filter(|r| {
            r.get("client_callable")
                .and_then(Value::as_bool)
                .unwrap_or(true)
        })
        .filter_map(|r| r.get("name").and_then(Value::as_str).map(ToOwned::to_owned))
        .collect();
    if !reducer_syms.is_empty() {
        out.push_str(&format!(
            "from .reducers import {}\n",
            reducer_syms.join(", ")
        ));
        exports.extend(reducer_syms);
    }

    out.push('\n');
    let quoted: Vec<String> = exports.iter().map(|e| format!("\"{e}\"")).collect();
    out.push_str(&format!("__all__ = [{}]\n", quoted.join(", ")));
    Ok(out)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;

    fn demo_schema() -> Value {
        serde_json::json!({
            "schema_version": 7,
            "document_version": 1,
            "tables": [{
                "name": "Task",
                "columns": [
                    { "name": "id", "type": "U64" },
                    { "name": "owner", "type": "Identity" },
                    { "name": "title", "type": "Str" },
                    { "name": "done", "type": "Bool" }
                ],
                "primary_key": [0]
            }],
            "reducers": [
                { "name": "add_task", "params": [{ "name": "title", "type": "String" }] },
                { "name": "sweep", "params": [], "client_callable": false }
            ]
        })
    }

    #[test]
    fn emits_typed_rows_decoders_and_reducer_wrappers() {
        let files = generate(&demo_schema()).unwrap();
        let tables = &files["tables.py"];
        assert!(tables.contains("class Task:"));
        assert!(tables.contains("id: int"));
        assert!(tables.contains("owner: str"));
        assert!(tables.contains("done: bool"));
        assert!(tables.contains("def decode_Task(row: bytes) -> Task:"));
        assert!(tables.contains("def table_schema_Task() -> TableSchema:"));

        let reducers = &files["reducers.py"];
        assert!(reducers.contains("async def add_task(db: Connection, title: str) -> None:"));
        // A schedule-only reducer is not emitted as a client wrapper.
        assert!(!reducers.contains("def sweep("));

        assert!(files.contains_key("py.typed"));
        assert!(files["__init__.py"].contains("from .tables import Task"));
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(generate(&demo_schema()), generate(&demo_schema()));
    }

    #[test]
    fn an_unmodelled_column_type_is_refused() {
        let schema = serde_json::json!({
            "schema_version": 1,
            "tables": [{
                "name": "T",
                "columns": [{ "name": "c", "type": "Wat" }],
                "primary_key": [0]
            }],
            "reducers": []
        });
        assert!(generate(&schema).unwrap_err().contains("unmodelled type"));
    }
}
