//! `fluxum generate --lang rust` (SPEC-011 SDK-050): typed row structs and
//! reducer wrappers emitted from the frozen `/schema` document, for use with
//! the `fluxum-sdk` client crate.
//!
//! # What is emitted
//!
//! A single generated module (`mod.rs`) carrying, per table, a `#[derive]`d
//! row struct with typed fields, a `decode` from FluxBIN bytes, and a
//! `table_schema()` that builds the SDK's [`fluxum_sdk::TableSchema`] (the
//! primary-key projection the cache needs, SDK-040); plus a `Reducers`
//! wrapper with one method per client-callable reducer, and `SCHEMA_VERSION`.
//!
//! # Why it references `fluxum_sdk`
//!
//! Unlike the TypeScript output — which declares the small surface it needs so
//! it typechecks before any runtime exists — the Rust bindings are compiled
//! *against* the `fluxum-sdk` crate they are used with, so they reference its
//! `FluxBinReader`, `TableSchema`, and `Connection` directly. There is no
//! "compiles alone" requirement for a Rust module that only exists inside a
//! crate that already depends on the SDK.
//!
//! # Determinism (SPEC-011 acceptance 10/11)
//!
//! A pure function of the document: tables, reducers and columns are emitted
//! in document order and the file map is a `BTreeMap`, so regeneration is
//! byte-identical and a saved `schema.json` yields exactly what a URL does.
//!
//! # Numeric types
//!
//! Rust has exact 64-bit integers, so unlike the TS target there is no
//! precision hazard: every `FluxType` maps to its natural Rust type.

use std::collections::BTreeMap;

use serde_json::Value;

fn header(schema_version: u64, document_version: u64) -> String {
    format!(
        "// Code generated by `fluxum generate --lang rust`. DO NOT EDIT.\n\
         //\n\
         // schema_version:   {schema_version}   (the module's schema — SPEC-010 MIG-001)\n\
         // document_version: {document_version}   (the /schema shape — frozen at T6.1)\n\
         //\n\
         // Re-run the generator after a schema change; edits here are lost.\n\n"
    )
}

/// Map a schema column type (`FluxType` name) to its Rust type.
pub fn column_type(flux: &str) -> &'static str {
    match flux {
        "Bool" => "bool",
        "I8" => "i8",
        "I16" => "i16",
        "I32" => "i32",
        "I64" => "i64",
        "U8" => "u8",
        "U16" => "u16",
        "U32" => "u32",
        "U64" | "EntityId" => "u64",
        "F32" => "f32",
        "F64" => "f64",
        "Str" => "String",
        "Bytes" => "Vec<u8>",
        "Identity" => "[u8; 32]",
        "ConnectionId" => "u128",
        "Timestamp" => "i64",
        // An unmodelled type is surfaced as raw bytes with a doc note rather
        // than guessed — the SDK's typed layer stops at the column it cannot
        // model, but never silently mistypes it.
        _ => "Vec<u8>",
    }
}

/// Whether a `FluxType` name has a modelled Rust decoding. An unmodelled type
/// cannot be positionally decoded (the reader would desync every column after
/// it), so generation refuses one rather than emit a broken `decode`.
fn is_modelled(flux: &str) -> bool {
    matches!(
        flux,
        "Bool"
            | "I8"
            | "I16"
            | "I32"
            | "I64"
            | "U8"
            | "U16"
            | "U32"
            | "U64"
            | "EntityId"
            | "F32"
            | "F64"
            | "Str"
            | "Bytes"
            | "Identity"
            | "ConnectionId"
            | "Timestamp"
    )
}

/// The bare `FluxBinReader` call reading one column of `flux` type — the read
/// half, without any `.to_owned()`/`.to_vec()` conversion.
fn reader_call(flux: &str) -> &'static str {
    match flux {
        "Bool" => "reader.read_bool()?",
        "I8" => "reader.read_i8()?",
        "I16" => "reader.read_i16()?",
        "I32" => "reader.read_i32()?",
        "I64" => "reader.read_i64()?",
        "U8" => "reader.read_u8()?",
        "U16" => "reader.read_u16()?",
        "U32" => "reader.read_u32()?",
        "U64" => "reader.read_u64()?",
        "EntityId" => "reader.read_entity_id()?",
        "F32" => "reader.read_f32()?",
        "F64" => "reader.read_f64()?",
        "Str" => "reader.read_str()?",
        "Bytes" => "reader.read_bytes()?",
        "Identity" => "reader.read_identity()?",
        "ConnectionId" => "reader.read_connection_id()?",
        "Timestamp" => "reader.read_timestamp()?",
        // Unreachable: generation refuses an unmodelled column (is_modelled).
        _ => "reader.read_bytes()?",
    }
}

/// The `FluxBinReader` call that reads one column into its [`column_type`]
/// value (adds the owning conversion for borrowed reads).
fn read_expr(flux: &str) -> String {
    let call = reader_call(flux);
    match flux {
        "Str" => format!("{call}.to_owned()"),
        "Bytes" => format!("{call}.to_vec()"),
        _ => call.to_owned(),
    }
}

/// Skip one column of `flux` type when projecting a primary key.
fn skip_stmt(flux: &str) -> String {
    format!("let _ = {};", reader_call(flux))
}

/// Map a reducer parameter's Rust source spelling to the Rust type a wrapper
/// takes. Parameters arrive already written in Rust, so most pass through; the
/// wrapper takes owned values to forward as `FluxValue`.
pub fn param_type(rust: &str) -> String {
    let rust = rust.replace(' ', "");
    match rust.as_str() {
        "&str" | "str" => "String".to_owned(),
        other => other.to_owned(),
    }
}

/// The `FluxValue` constructor expression for a reducer argument of Rust type
/// `rust`, given the binding name `arg`.
fn flux_value_expr(rust: &str, arg: &str) -> String {
    let rust = rust.replace(' ', "");
    match rust.as_str() {
        "bool" => format!("fluxum_sdk::protocol::FluxValue::Bool({arg})"),
        "i8" | "i16" | "i32" | "i64" => {
            format!("fluxum_sdk::protocol::FluxValue::I64(i64::from({arg}))")
        }
        "u8" | "u16" | "u32" => format!("fluxum_sdk::protocol::FluxValue::I64(i64::from({arg}))"),
        "u64" => format!("fluxum_sdk::protocol::FluxValue::I64({arg} as i64)"),
        "f32" => format!("fluxum_sdk::protocol::FluxValue::F64(f64::from({arg}))"),
        "f64" => format!("fluxum_sdk::protocol::FluxValue::F64({arg})"),
        "String" | "&str" | "str" => format!("fluxum_sdk::protocol::FluxValue::Str({arg})"),
        "Identity" => format!("fluxum_sdk::protocol::FluxValue::Identity({arg})"),
        "Timestamp" => format!("fluxum_sdk::protocol::FluxValue::Timestamp({arg})"),
        // Anything else is forwarded as bytes — the reducer arg encoder on the
        // server side rejects a mismatch, so this stays honest.
        _ => format!("fluxum_sdk::protocol::FluxValue::Bytes({arg})"),
    }
}

fn doc_comment(lines: &[String], indent: &str) -> String {
    lines.iter().map(|l| format!("{indent}/// {l}\n")).collect()
}

/// Generate the Rust binding file(s) from a `/schema` document. Returns
/// `filename -> contents`, deterministic for a given document.
pub fn generate(schema: &Value) -> Result<BTreeMap<String, String>, String> {
    let schema_version = schema
        .get("schema_version")
        .and_then(Value::as_u64)
        .ok_or("schema document has no `schema_version`")?;
    let document_version = schema
        .get("document_version")
        .and_then(Value::as_u64)
        .unwrap_or(1);
    let banner = header(schema_version, document_version);

    let tables = schema
        .get("tables")
        .and_then(Value::as_array)
        .ok_or("schema document has no `tables` array")?;
    let reducers = schema
        .get("reducers")
        .and_then(Value::as_array)
        .ok_or("schema document has no `reducers` array")?;

    let mut out = String::from(&banner);
    out.push_str(
        "#![allow(clippy::all, dead_code)]\n\
         //! Generated Fluxum bindings for this module.\n\
         //!\n\
         //! These types are a menu — a consumer uses the tables and reducers it\n\
         //! needs, so unused ones are expected, not a warning.\n\n\
         use fluxum_sdk::protocol::FluxBinReader;\n\
         use fluxum_sdk::{TableSchema, cache::TableDiff};\n\n",
    );
    out.push_str(&format!(
        "/// The module schema version these bindings were generated from.\n\
         pub const SCHEMA_VERSION: u32 = {schema_version};\n\n"
    ));

    for table in tables {
        out.push_str(&table_struct(table)?);
    }
    out.push_str(&reducers_wrapper(reducers)?);

    let mut files = BTreeMap::new();
    files.insert("mod.rs".to_owned(), out);
    Ok(files)
}

fn table_struct(table: &Value) -> Result<String, String> {
    let name = table
        .get("name")
        .and_then(Value::as_str)
        .ok_or("table has no name")?;
    let columns = table
        .get("columns")
        .and_then(Value::as_array)
        .ok_or_else(|| format!("table `{name}` has no columns"))?;
    let pk_ordinals: Vec<usize> = table
        .get("primary_key")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(Value::as_u64)
                .map(|n| n as usize)
                .collect()
        })
        .unwrap_or_default();
    let pk_end = pk_ordinals.iter().copied().max().map_or(0, |m| m + 1);
    let pk_names: Vec<&str> = pk_ordinals
        .iter()
        .filter_map(|i| columns.get(*i))
        .filter_map(|c| c.get("name").and_then(Value::as_str))
        .collect();
    let auto_inc = table.get("auto_inc").and_then(Value::as_str);

    let mut doc = vec![format!("Row of the `{name}` table.")];
    if !pk_names.is_empty() {
        doc.push(format!("Primary key: `{}`.", pk_names.join("`, `")));
    }
    if let Some(auto_inc) = auto_inc {
        doc.push(format!(
            "`{auto_inc}` is auto-inc: send 0 on insert and the server assigns it."
        ));
    }

    let mut out = String::new();
    out.push_str(&doc_comment(&doc, ""));
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));
    for column in columns {
        let col_name = column
            .get("name")
            .and_then(Value::as_str)
            .ok_or_else(|| format!("table `{name}` has an unnamed column"))?;
        let ty = column
            .get("type")
            .and_then(Value::as_str)
            .ok_or_else(|| format!("column `{name}.{col_name}` has no type"))?;
        if !is_modelled(ty) {
            return Err(format!(
                "column `{name}.{col_name}` has unmodelled type `{ty}`: the Rust generator \
                 cannot positionally decode it. Model the type or remove the column."
            ));
        }
        let mut cdoc = Vec::new();
        if pk_names.contains(&col_name) {
            cdoc.push("Primary key.".to_owned());
        }
        if auto_inc == Some(col_name) {
            cdoc.push("Auto-increment.".to_owned());
        }
        out.push_str(&doc_comment(&cdoc, "    "));
        out.push_str(&format!("    pub {col_name}: {},\n", column_type(ty)));
    }
    out.push_str("}\n\n");

    // decode + table_schema
    out.push_str(&format!("impl {name} {{\n"));
    out.push_str(
        "    /// The table name as it appears on the wire.\n\
         \x20   pub const TABLE: &'static str = \"",
    );
    out.push_str(name);
    out.push_str("\";\n\n");

    out.push_str(
        "    /// Decode one row from its FluxBIN bytes (columns in declaration order).\n\
         \x20   pub fn decode(bytes: &[u8]) -> Result<Self, fluxum_sdk::protocol::FluxBinError> {\n\
         \x20       let mut reader = FluxBinReader::new(bytes);\n\
         \x20       Ok(Self {\n",
    );
    for column in columns {
        let col_name = column.get("name").and_then(Value::as_str).unwrap_or("_");
        let ty = column.get("type").and_then(Value::as_str).unwrap_or("");
        out.push_str(&format!("            {col_name}: {},\n", read_expr(ty)));
    }
    out.push_str("        })\n    }\n\n");

    // table_schema(): primary-key projection over the first `pk_end` columns.
    let pk_types: Vec<&str> = (0..pk_end)
        .filter_map(|i| columns.get(i))
        .filter_map(|c| c.get("type").and_then(Value::as_str))
        .collect();
    let skips: String = pk_types
        .iter()
        .map(|ty| format!("                {}\n", skip_stmt(ty)))
        .collect();
    out.push_str(
        "    /// The SDK cache hooks for this table: the primary-key projection\n\
         \x20   /// (SDK-040), read as the leading key columns' raw bytes.\n\
         \x20   pub fn table_schema() -> TableSchema {\n\
         \x20       fn pk(bytes: &[u8]) -> Vec<u8> {\n\
         \x20           fn project(bytes: &[u8]) -> Result<usize, fluxum_sdk::protocol::FluxBinError> {\n\
         \x20               let mut reader = FluxBinReader::new(bytes);\n",
    );
    out.push_str(&skips);
    out.push_str(
        "                Ok(bytes.len() - reader.remaining())\n\
         \x20           }\n\
         \x20           let end = project(bytes).unwrap_or(bytes.len());\n\
         \x20           bytes[..end].to_vec()\n\
         \x20       }\n\
         \x20       TableSchema {\n\
         \x20           name: Self::TABLE.to_owned(),\n\
         \x20           pk_of_row: Box::new(pk),\n\
         \x20           pk_of_delete: Box::new(pk),\n\
         \x20       }\n\
         \x20   }\n",
    );

    // A tiny convenience: pull this table's inserted rows out of a diff.
    out.push_str(
        "\n    /// Decode every inserted row this table carried in a diff.\n\
         \x20   pub fn inserts(diff: &TableDiff) -> Result<Vec<Self>, fluxum_sdk::protocol::FluxBinError> {\n\
         \x20       diff.inserts.iter().map(|r| Self::decode(r)).collect()\n\
         \x20   }\n",
    );
    out.push_str("}\n\n");
    Ok(out)
}

fn reducers_wrapper(reducers: &[Value]) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(
        "/// Typed wrappers for this module's client-callable reducers.\n\
         ///\n\
         /// Construct with a `&Connection`; each method forwards its arguments\n\
         /// positionally, exactly as the server declares them.\n\
         pub struct Reducers<'a> {\n\
         \x20   conn: &'a fluxum_sdk::Connection,\n\
         }\n\n\
         impl<'a> Reducers<'a> {\n\
         \x20   /// Wrap a live connection.\n\
         \x20   pub fn new(conn: &'a fluxum_sdk::Connection) -> Self {\n\
         \x20       Self { conn }\n\
         \x20   }\n",
    );

    for reducer in reducers {
        let name = reducer
            .get("name")
            .and_then(Value::as_str)
            .ok_or("reducer has no name")?;
        if !reducer
            .get("client_callable")
            .and_then(Value::as_bool)
            .unwrap_or(true)
        {
            continue;
        }
        let params = reducer
            .get("params")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();
        let mut signature = Vec::new();
        let mut arg_exprs = Vec::new();
        for param in &params {
            let pname = param
                .get("name")
                .and_then(Value::as_str)
                .ok_or_else(|| format!("reducer `{name}` has an unnamed parameter"))?;
            let ty = param.get("type").and_then(Value::as_str).unwrap_or("");
            signature.push(format!("{pname}: {}", param_type(ty)));
            arg_exprs.push(flux_value_expr(ty, pname));
        }

        let mut doc = vec![format!("Call the `{name}` reducer.")];
        if let Some(rate) = reducer.get("max_rate_per_sec").and_then(Value::as_u64)
            && rate > 0
        {
            doc.push(format!(
                "Rate-limited to {rate}/s per identity (RED-050); over that the call errors with a retryable 429."
            ));
        }
        out.push('\n');
        out.push_str(&doc_comment(&doc, "    "));
        out.push_str(&format!(
            "    pub fn {name}(&self, {}) -> Result<(), fluxum_sdk::ClientError> {{\n\
             \x20       self.conn.call_reducer(\"{name}\", vec![{}])\n\
             \x20   }}\n",
            signature.join(", "),
            arg_exprs.join(", "),
        ));
    }
    out.push_str("}\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    fn schema() -> Value {
        serde_json::json!({
            "schema_version": 3,
            "document_version": 1,
            "tables": [{
                "name": "Task",
                "columns": [
                    { "name": "id", "type": "U64" },
                    { "name": "owner", "type": "Identity" },
                    { "name": "title", "type": "Str" },
                    { "name": "done", "type": "Bool" }
                ],
                "primary_key": [0],
                "auto_inc": "id",
                "visibility": { "kind": "owner_only", "column": "owner" }
            }],
            "reducers": [
                {
                    "name": "complete_task",
                    "params": [{ "name": "task_id", "type": "u64" }],
                    "client_callable": true,
                    "max_rate_per_sec": 5
                },
                {
                    "name": "tick_only",
                    "params": [],
                    "client_callable": false,
                    "max_rate_per_sec": 0
                }
            ]
        })
    }

    #[test]
    fn every_flux_type_maps_to_its_natural_rust_type() {
        assert_eq!(column_type("U64"), "u64");
        assert_eq!(column_type("I64"), "i64");
        assert_eq!(column_type("Bool"), "bool");
        assert_eq!(column_type("Str"), "String");
        assert_eq!(column_type("Identity"), "[u8; 32]");
        assert_eq!(column_type("ConnectionId"), "u128");
    }

    #[test]
    fn generation_is_byte_identical_when_repeated() {
        assert_eq!(generate(&schema()).unwrap(), generate(&schema()).unwrap());
    }

    #[test]
    fn the_file_carries_the_do_not_edit_header_and_schema_version() {
        let files = generate(&schema()).unwrap();
        let m = &files["mod.rs"];
        assert!(m.starts_with("// Code generated by"), "{m}");
        assert!(m.contains("DO NOT EDIT"));
        assert!(m.contains("schema_version:   3"));
        assert!(m.contains("pub const SCHEMA_VERSION: u32 = 3;"));
    }

    #[test]
    fn a_table_becomes_a_typed_struct_with_decode_and_schema() {
        let files = generate(&schema()).unwrap();
        let m = &files["mod.rs"];
        assert!(m.contains("pub struct Task {"), "{m}");
        assert!(m.contains("pub id: u64,"), "{m}");
        assert!(m.contains("pub owner: [u8; 32],"), "{m}");
        assert!(m.contains("pub done: bool,"), "{m}");
        assert!(m.contains("pub fn decode(bytes: &[u8])"), "{m}");
        assert!(m.contains("reader.read_u64()?"), "{m}");
        assert!(m.contains("reader.read_identity()?"), "{m}");
        assert!(m.contains("pub fn table_schema() -> TableSchema"), "{m}");
    }

    #[test]
    fn only_client_callable_reducers_get_a_method() {
        let files = generate(&schema()).unwrap();
        let m = &files["mod.rs"];
        assert!(
            m.contains(
                "pub fn complete_task(&self, task_id: u64) -> Result<(), fluxum_sdk::ClientError>"
            ),
            "{m}"
        );
        assert!(
            m.contains("self.conn.call_reducer(\"complete_task\""),
            "{m}"
        );
        assert!(!m.contains("tick_only"), "{m}");
        assert!(m.contains("5/s"), "{m}");
    }

    #[test]
    fn a_document_without_a_schema_version_is_refused() {
        let mut bad = schema();
        bad.as_object_mut().unwrap().remove("schema_version");
        assert!(generate(&bad).is_err());
    }
}
