//! `fluxum generate --lang typescript` (SPEC-011 SDK-021, FR-82): typed
//! table interfaces and reducer wrappers emitted from the frozen `/schema`
//! document (T6.1).
//!
//! # What is emitted, and why it compiles alone
//!
//! Three files — `types.ts` (a row interface per table), `reducers.ts` (a
//! typed wrapper per client-callable reducer), `index.ts` (re-exports) —
//! plus `client.ts`, the *small* interface the wrappers call through.
//!
//! That last file is what lets the output satisfy "compiles under
//! `tsc --strict` with zero manual stubs": the generated code depends on a
//! surface it also declares, so a consumer can typecheck and review generated
//! bindings before any runtime exists, and the runtime later satisfies the
//! same interface rather than the generator being rewritten around it.
//!
//! # Determinism (SPEC-011 acceptance 10/11)
//!
//! Everything here is a pure function of the schema document. Tables,
//! reducers and columns are emitted in the document's order — which the
//! server already sorts — and the file map is a `BTreeMap`, so regenerating
//! twice is byte-identical and generating from a saved `schema.json` gives
//! exactly what generating from a URL gives.
//!
//! # Numeric types
//!
//! 64-bit integers map to `bigint`, not `number`: `u64`/`i64` exceed
//! `Number.MAX_SAFE_INTEGER`, and silently losing precision on a primary key
//! is the kind of bug that surfaces months later as two rows colliding.
//! Everything ≤ 32 bits maps to `number`.

use std::collections::BTreeMap;

use serde_json::Value;

/// The generated-file banner (SPEC-011 acceptance 11): every file says it is
/// generated and from which schema version, so a stray hand-edit is obvious
/// in review and a stale binding is identifiable at a glance.
fn header(schema_version: u64, document_version: u64) -> String {
    format!(
        "// Code generated by `fluxum generate --lang typescript`. DO NOT EDIT.\n\
         //\n\
         // schema_version:   {schema_version}   (the module's schema — SPEC-010 MIG-001)\n\
         // document_version: {document_version}   (the /schema shape — frozen at T6.1)\n\
         //\n\
         // Re-run the generator after a schema change; edits here are lost.\n\n"
    )
}

/// Map a schema column type (`FluxType` name) to its TypeScript type.
pub fn column_type(flux: &str) -> String {
    match flux {
        "Bool" => "boolean",
        // ≤ 32-bit integers and both floats fit a JS number exactly.
        "I8" | "I16" | "I32" | "U8" | "U16" | "U32" | "F32" | "F64" => "number",
        // 64-bit: `number` would silently lose precision.
        "I64" | "U64" | "EntityId" => "bigint",
        "Str" => "string",
        "Bytes" => "Uint8Array",
        "Identity" => "Identity",
        "ConnectionId" => "ConnectionId",
        "Timestamp" => "Timestamp",
        // An unmodelled type is surfaced as `unknown` rather than guessed:
        // `any` would silently disable the checking the SDK exists to give.
        _ => "unknown",
    }
    .to_owned()
}

/// Map a reducer parameter's **Rust source spelling** to its TypeScript type.
/// Parameter types arrive as written in the module (`u32`, `String`), not as
/// `FluxType` names.
pub fn param_type(rust: &str) -> String {
    // Normalize the spacing rustfmt/`stringify!` may leave behind.
    let rust = rust.replace(' ', "");
    let inner = |prefix: &str| -> Option<String> {
        rust.strip_prefix(prefix)
            .and_then(|r| r.strip_suffix('>'))
            .map(ToOwned::to_owned)
    };
    if let Some(inner) = inner("Option<") {
        return format!("{} | null", param_type(&inner));
    }
    if let Some(inner) = inner("Vec<") {
        return if inner == "u8" {
            "Uint8Array".to_owned()
        } else {
            format!("{}[]", param_type(&inner))
        };
    }
    match rust.as_str() {
        "bool" => "boolean",
        "i8" | "i16" | "i32" | "u8" | "u16" | "u32" | "f32" | "f64" => "number",
        "i64" | "u64" | "i128" | "u128" | "usize" | "isize" => "bigint",
        "String" | "&str" | "str" => "string",
        "Identity" => "Identity",
        "ConnectionId" => "ConnectionId",
        "Timestamp" => "Timestamp",
        _ => "unknown",
    }
    .to_owned()
}

/// A TS identifier safe to use as a method name: `snake_case` reducer names
/// are kept verbatim (they are already valid identifiers and matching the
/// server name keeps the mapping obvious in a stack trace).
fn method_name(reducer: &str) -> &str {
    reducer
}

fn doc_comment(lines: &[String], indent: &str) -> String {
    if lines.is_empty() {
        return String::new();
    }
    let body: String = lines.iter().map(|l| format!("{indent} * {l}\n")).collect();
    format!("{indent}/**\n{body}{indent} */\n")
}

/// Generate the TypeScript binding files from a `/schema` document.
/// Returns `filename -> contents`, deterministic for a given document.
pub fn generate(schema: &Value) -> Result<BTreeMap<String, String>, String> {
    let schema_version = schema
        .get("schema_version")
        .and_then(Value::as_u64)
        .ok_or("schema document has no `schema_version`")?;
    let document_version = schema
        .get("document_version")
        .and_then(Value::as_u64)
        .unwrap_or(1);
    let banner = header(schema_version, document_version);

    let tables = schema
        .get("tables")
        .and_then(Value::as_array)
        .ok_or("schema document has no `tables` array")?;
    let reducers = schema
        .get("reducers")
        .and_then(Value::as_array)
        .ok_or("schema document has no `reducers` array")?;

    let mut files = BTreeMap::new();
    files.insert("client.ts".to_owned(), client_ts(&banner));
    files.insert("types.ts".to_owned(), types_ts(&banner, tables)?);
    files.insert("decoders.ts".to_owned(), decoders_ts(&banner, tables)?);
    files.insert(
        "reducers.ts".to_owned(),
        reducers_ts(&banner, reducers, schema_version)?,
    );
    files.insert("index.ts".to_owned(), index_ts(&banner));
    Ok(files)
}

/// The FluxBIN reader method name for a column type, as exposed by the SDK's
/// `RowReader.read(type)`. The reader takes the `FluxType` name verbatim, so
/// this only needs to validate that the type is one the reader models — an
/// unmodelled column is refused at generation rather than emitted as a decode
/// that would desync every column after it.
fn is_decodable(flux: &str) -> bool {
    matches!(
        flux,
        "Bool"
            | "I8"
            | "I16"
            | "I32"
            | "I64"
            | "U8"
            | "U16"
            | "U32"
            | "U64"
            | "EntityId"
            | "F32"
            | "F64"
            | "Str"
            | "Bytes"
            | "Identity"
            | "ConnectionId"
            | "Timestamp"
    )
}

/// Emit typed per-table decoders (`decode<Table>(row) -> <Table>`), unlike the
/// runtime-free `types.ts` these DO import the SDK's schema-agnostic
/// `decodeRow` — a generated decoder is a *with-runtime* convenience (it is
/// what lets an application drop hand-written FluxBIN readers), so it is a
/// separate file from the `tsc`-alone binding set.
fn decoders_ts(banner: &str, tables: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str(
        "import { decodeRow } from '@hivehub/fluxum';\n\
         import type { FluxType } from '@hivehub/fluxum';\n",
    );
    // Import each table interface so the return types are the generated ones.
    let names: Vec<&str> = tables
        .iter()
        .filter_map(|t| t.get("name").and_then(Value::as_str))
        .collect();
    if !names.is_empty() {
        out.push_str(&format!("import type {{ {} }} from './types';\n", names.join(", ")));
    }
    out.push('\n');

    for table in tables {
        let name = table
            .get("name")
            .and_then(Value::as_str)
            .ok_or("table has no name")?;
        let columns = table
            .get("columns")
            .and_then(Value::as_array)
            .ok_or_else(|| format!("table `{name}` has no columns"))?;

        // The column descriptor list the schema-agnostic reader walks.
        let mut descriptors = Vec::new();
        for column in columns {
            let col_name = column
                .get("name")
                .and_then(Value::as_str)
                .ok_or_else(|| format!("table `{name}` has an unnamed column"))?;
            let ty = column
                .get("type")
                .and_then(Value::as_str)
                .ok_or_else(|| format!("column `{name}.{col_name}` has no type"))?;
            if !is_decodable(ty) {
                return Err(format!(
                    "column `{name}.{col_name}` has unmodelled type `{ty}`: the row decoder \
                     cannot read it. Model the type or remove the column."
                ));
            }
            descriptors.push(format!("{{ name: '{col_name}', type: '{ty}' as FluxType }}"));
        }

        out.push_str(&doc_comment(
            &[format!("Column layout of `{name}`, in FluxBIN wire order.")],
            "",
        ));
        out.push_str(&format!(
            "const {name}Columns = [{}] as const;\n\n",
            descriptors.join(", ")
        ));
        out.push_str(&doc_comment(
            &[
                format!("Decode one `{name}` row from its FluxBIN bytes."),
                "The columns are read in declaration order; a length mismatch throws.".to_owned(),
            ],
            "",
        ));
        out.push_str(&format!(
            "export function decode{name}(row: Uint8Array): {name} {{\n\
             \x20 return decodeRow(row, {name}Columns) as unknown as {name};\n\
             }}\n\n"
        ));
    }
    Ok(out)
}

/// The interface the generated wrappers call through, plus the branded
/// scalar aliases the row types use.
fn client_ts(banner: &str) -> String {
    format!(
        "{banner}\
/** A 256-bit client identity (SPEC-009), hex-encoded. */\n\
export type Identity = string & {{ readonly __brand: 'Identity' }};\n\n\
/** A connection id (128-bit), hex-encoded. */\n\
export type ConnectionId = string & {{ readonly __brand: 'ConnectionId' }};\n\n\
/** Microseconds since the Unix epoch. */\n\
export type Timestamp = bigint & {{ readonly __brand?: 'Timestamp' }};\n\n\
/**\n\
 * The slice of the Fluxum client the generated reducer wrappers need.\n\
 *\n\
 * Declared here rather than imported so the generated bindings typecheck on\n\
 * their own; the runtime client satisfies this structurally.\n\
 */\n\
export interface ReducerCaller {{\n\
\x20 /**\n\
\x20  * Invoke a reducer by name with positional arguments.\n\
\x20  * Rejects with the server's typed error (SPEC-028) on failure.\n\
\x20  */\n\
\x20 callReducer(name: string, args: readonly unknown[]): Promise<void>;\n\
}}\n"
    )
}

fn types_ts(banner: &str, tables: &[Value]) -> Result<String, String> {
    let mut out = String::from(banner);
    out.push_str("import type { ConnectionId, Identity, Timestamp } from './client';\n\n");
    // Re-export so a consumer importing only `types` still gets the scalars.
    out.push_str("export type { ConnectionId, Identity, Timestamp };\n\n");

    for table in tables {
        let name = table
            .get("name")
            .and_then(Value::as_str)
            .ok_or("table has no name")?;
        let columns = table
            .get("columns")
            .and_then(Value::as_array)
            .ok_or_else(|| format!("table `{name}` has no columns"))?;
        let pk_ordinals: Vec<usize> = table
            .get("primary_key")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_u64)
                    .map(|n| n as usize)
                    .collect()
            })
            .unwrap_or_default();
        let pk_names: Vec<&str> = pk_ordinals
            .iter()
            .filter_map(|i| columns.get(*i))
            .filter_map(|c| c.get("name").and_then(Value::as_str))
            .collect();
        let auto_inc = table.get("auto_inc").and_then(Value::as_str);
        let visibility = table
            .get("visibility")
            .and_then(|v| v.get("kind"))
            .and_then(Value::as_str)
            .unwrap_or("public_all");

        let mut doc = vec![format!("Row of the `{name}` table.")];
        if !pk_names.is_empty() {
            doc.push(format!("Primary key: `{}`.", pk_names.join("`, `")));
        }
        if let Some(auto_inc) = auto_inc {
            doc.push(format!(
                "`{auto_inc}` is auto-inc: send 0 on insert and the server assigns it."
            ));
        }
        if visibility != "public_all" {
            doc.push(format!("Row visibility: `{visibility}` (SPEC-005)."));
        }
        out.push_str(&doc_comment(&doc, ""));
        out.push_str(&format!("export interface {name} {{\n"));
        for column in columns {
            let col_name = column
                .get("name")
                .and_then(Value::as_str)
                .ok_or_else(|| format!("table `{name}` has an unnamed column"))?;
            let ty = column
                .get("type")
                .and_then(Value::as_str)
                .ok_or_else(|| format!("column `{name}.{col_name}` has no type"))?;
            let mut column_doc = Vec::new();
            if pk_names.contains(&col_name) {
                column_doc.push("Primary key.".to_owned());
            }
            if auto_inc == Some(col_name) {
                column_doc.push("Auto-increment.".to_owned());
            }
            out.push_str(&doc_comment(&column_doc, "  "));
            out.push_str(&format!("  {col_name}: {};\n", column_type(ty)));
        }
        out.push_str("}\n\n");

        // The primary-key tuple type: what a cache or a targeted read keys on.
        if !pk_names.is_empty() {
            let parts: Vec<String> = pk_ordinals
                .iter()
                .filter_map(|i| columns.get(*i))
                .filter_map(|c| c.get("type").and_then(Value::as_str))
                .map(column_type)
                .collect();
            out.push_str(&doc_comment(
                &[format!("Primary key of `{name}`, in declaration order.")],
                "",
            ));
            out.push_str(&format!(
                "export type {name}Key = [{}];\n\n",
                parts.join(", ")
            ));
        }
    }
    Ok(out)
}

fn reducers_ts(banner: &str, reducers: &[Value], schema_version: u64) -> Result<String, String> {
    // Import only the scalar aliases the signatures below actually mention:
    // a generated file must compile under `noUnusedLocals`, and an unused
    // type import is an error there.
    let mut used: Vec<&str> = Vec::new();
    let signatures: String = reducers
        .iter()
        .filter_map(|r| r.get("params").and_then(Value::as_array))
        .flatten()
        .filter_map(|p| p.get("type").and_then(Value::as_str))
        .map(param_type)
        .collect();
    for alias in ["ConnectionId", "Identity", "Timestamp"] {
        if signatures.contains(alias) {
            used.push(alias);
        }
    }
    used.push("ReducerCaller");
    used.sort_unstable();

    let mut out = String::from(banner);
    out.push_str(&format!(
        "import type {{ {} }} from './client';\n\n",
        used.join(", ")
    ));
    out.push_str(&format!(
        "/** The module schema version these wrappers were generated from. */\n\
         export const SCHEMA_VERSION = {schema_version};\n\n"
    ));
    out.push_str(
        "/**\n\
         * Typed wrappers for this module's client-callable reducers.\n\
         *\n\
         * Construct with any client satisfying `ReducerCaller`; each method\n\
         * forwards its arguments positionally, exactly as the server declares\n\
         * them.\n\
         */\n\
         export class Reducers {\n\
         \x20 constructor(private readonly client: ReducerCaller) {}\n",
    );

    for reducer in reducers {
        let name = reducer
            .get("name")
            .and_then(Value::as_str)
            .ok_or("reducer has no name")?;
        // A schedule-only reducer answers a client 403 (RED-025); emitting a
        // method for it would be an invitation to call something that always
        // fails.
        if !reducer
            .get("client_callable")
            .and_then(Value::as_bool)
            .unwrap_or(true)
        {
            continue;
        }
        let params = reducer
            .get("params")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();
        let mut signature = Vec::new();
        let mut argument_names = Vec::new();
        for param in &params {
            let param_name = param
                .get("name")
                .and_then(Value::as_str)
                .ok_or_else(|| format!("reducer `{name}` has an unnamed parameter"))?;
            let ty = param.get("type").and_then(Value::as_str).unwrap_or("");
            signature.push(format!("{param_name}: {}", param_type(ty)));
            argument_names.push(param_name.to_owned());
        }

        let mut doc = vec![format!("Call the `{name}` reducer.")];
        if let Some(rate) = reducer.get("max_rate_per_sec").and_then(Value::as_u64)
            && rate > 0
        {
            doc.push(format!(
                "Rate-limited to {rate}/s per identity (RED-050); over that the call rejects with a retryable 429."
            ));
        }
        out.push('\n');
        out.push_str(&doc_comment(&doc, "  "));
        out.push_str(&format!(
            "  {}({}): Promise<void> {{\n    return this.client.callReducer('{name}', [{}]);\n  }}\n",
            method_name(name),
            signature.join(", "),
            argument_names.join(", "),
        ));
    }
    out.push_str("}\n");
    Ok(out)
}

fn index_ts(banner: &str) -> String {
    format!(
        "{banner}\
export * from './client';\n\
export * from './types';\n\
export * from './decoders';\n\
export * from './reducers';\n"
    )
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    fn schema() -> Value {
        serde_json::json!({
            "schema_version": 3,
            "document_version": 1,
            "tables": [{
                "name": "Task",
                "columns": [
                    { "name": "id", "type": "U64" },
                    { "name": "owner", "type": "Identity" },
                    { "name": "title", "type": "Str" },
                    { "name": "done", "type": "Bool" }
                ],
                "primary_key": [0],
                "auto_inc": "id",
                "visibility": { "kind": "owner_only", "column": "owner" }
            }],
            "reducers": [
                {
                    "name": "complete_task",
                    "params": [{ "name": "task_id", "type": "u64" }],
                    "client_callable": true,
                    "max_rate_per_sec": 5
                },
                {
                    "name": "tick_only",
                    "params": [],
                    "client_callable": false,
                    "max_rate_per_sec": 0
                }
            ]
        })
    }

    #[test]
    fn sixty_four_bit_integers_are_bigint_not_number() {
        // The whole point: a u64 pk in a JS `number` silently collides.
        assert_eq!(column_type("U64"), "bigint");
        assert_eq!(column_type("I64"), "bigint");
        assert_eq!(param_type("u64"), "bigint");
        // ...while everything that fits stays a plain number.
        assert_eq!(column_type("U32"), "number");
        assert_eq!(column_type("F64"), "number");
        assert_eq!(param_type("i32"), "number");
    }

    #[test]
    fn param_types_handle_the_rust_spellings_that_actually_appear() {
        assert_eq!(param_type("String"), "string");
        assert_eq!(param_type("bool"), "boolean");
        assert_eq!(param_type("Vec < u8 >"), "Uint8Array");
        assert_eq!(param_type("Vec<String>"), "string[]");
        assert_eq!(param_type("Option < u32 >"), "number | null");
        // An unmodelled type is `unknown`, never `any` — `any` would switch
        // off exactly the checking this SDK exists to provide.
        assert_eq!(param_type("MyCustomThing"), "unknown");
    }

    #[test]
    fn generation_is_byte_identical_when_repeated() {
        let a = generate(&schema()).unwrap();
        let b = generate(&schema()).unwrap();
        assert_eq!(a, b, "regeneration must be byte-identical (acceptance 10)");
    }

    #[test]
    fn every_file_carries_the_do_not_edit_header_and_schema_version() {
        for (name, contents) in generate(&schema()).unwrap() {
            assert!(
                contents.starts_with("// Code generated by"),
                "{name} lacks the generated banner"
            );
            assert!(contents.contains("DO NOT EDIT"), "{name}");
            assert!(
                contents.contains("schema_version:   3"),
                "{name} lacks the schema version"
            );
        }
    }

    #[test]
    fn a_table_becomes_a_typed_interface_with_its_key() {
        let files = generate(&schema()).unwrap();
        let types = &files["types.ts"];
        assert!(types.contains("export interface Task {"), "{types}");
        assert!(types.contains("id: bigint;"), "{types}");
        assert!(types.contains("owner: Identity;"), "{types}");
        assert!(types.contains("done: boolean;"), "{types}");
        assert!(types.contains("export type TaskKey = [bigint];"), "{types}");
        // The visibility rule is documented, not silently dropped.
        assert!(types.contains("owner_only"), "{types}");
        assert!(types.contains("auto-inc"), "{types}");
    }

    #[test]
    fn only_client_callable_reducers_get_a_method() {
        let files = generate(&schema()).unwrap();
        let reducers = &files["reducers.ts"];
        assert!(
            reducers.contains("complete_task(task_id: bigint): Promise<void>"),
            "{reducers}"
        );
        assert!(
            reducers.contains("this.client.callReducer('complete_task', [task_id])"),
            "{reducers}"
        );
        // A schedule-only reducer answers clients 403 — emitting a method for
        // it would invite a call that always fails.
        assert!(!reducers.contains("tick_only"), "{reducers}");
        // The declared rate limit is documented on the method.
        assert!(reducers.contains("5/s"), "{reducers}");
    }

    #[test]
    fn reducers_import_only_the_scalars_they_use() {
        // `noUnusedLocals` makes an unused type import a compile error, so the
        // import list is derived from the signatures rather than fixed. The
        // fixture's only param is a `u64` → no scalar alias is needed.
        let files = generate(&schema()).unwrap();
        let reducers = &files["reducers.ts"];
        assert!(
            reducers.contains("import type { ReducerCaller } from './client';"),
            "{reducers}"
        );

        // Add an Identity-typed param and it appears — and only then.
        let mut with_identity = schema();
        with_identity["reducers"][0]["params"] = serde_json::json!([
            { "name": "who", "type": "Identity" }
        ]);
        let files = generate(&with_identity).unwrap();
        let reducers = &files["reducers.ts"];
        assert!(
            reducers.contains("import type { Identity, ReducerCaller } from './client';"),
            "{reducers}"
        );
        assert!(reducers.contains("who: Identity"), "{reducers}");
    }

    #[test]
    fn a_document_without_a_schema_version_is_refused() {
        let mut bad = schema();
        bad.as_object_mut().unwrap().remove("schema_version");
        assert!(generate(&bad).is_err());
    }

    #[test]
    fn a_table_gets_a_typed_row_decoder() {
        // The decoder closes the "hand-written decoders" gap: an application
        // gets a typed `decodeTask(bytes): Task` from codegen, not by
        // hand-listing columns. It reuses the runtime's schema-agnostic
        // `decodeRow`, so it lives in its own file rather than the tsc-alone set.
        let files = generate(&schema()).unwrap();
        let decoders = &files["decoders.ts"];
        assert!(decoders.contains("import { decodeRow } from '@hivehub/fluxum';"), "{decoders}");
        assert!(decoders.contains("import type { Task } from './types';"), "{decoders}");
        assert!(
            decoders.contains("{ name: 'id', type: 'U64' as FluxType }"),
            "{decoders}"
        );
        assert!(
            decoders.contains("export function decodeTask(row: Uint8Array): Task {"),
            "{decoders}"
        );
        assert!(
            decoders.contains("return decodeRow(row, TaskColumns) as unknown as Task;"),
            "{decoders}"
        );
    }

    #[test]
    fn an_unmodelled_column_is_refused_by_the_decoder() {
        let mut bad = schema();
        bad["tables"][0]["columns"][2]["type"] = serde_json::json!("SomeFutureType");
        // types.ts tolerates it as `unknown`, but a decoder cannot read it —
        // so generation fails rather than emit a decode that desyncs.
        assert!(generate(&bad).is_err());
    }
}
